/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevlogIndexRouteImport } from './routes/devlog/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DevlogSlugRouteImport } from './routes/devlog/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiWaitlistRouteImport } from './routes/api/waitlist'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiOgDevlogSlugDotwebpRouteImport } from './routes/api/og/devlog.$slug[.]webp'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevlogIndexRoute = DevlogIndexRouteImport.update({
  id: '/devlog/',
  path: '/devlog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DevlogSlugRoute = DevlogSlugRouteImport.update({
  id: '/devlog/$slug',
  path: '/devlog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaitlistRoute = ApiWaitlistRouteImport.update({
  id: '/api/waitlist',
  path: '/api/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgDevlogSlugDotwebpRoute = ApiOgDevlogSlugDotwebpRouteImport.update({
  id: '/api/og/devlog/$slug.webp',
  path: '/api/og/devlog/$slug.webp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/waitlist': typeof WaitlistRoute
  '/api/search': typeof ApiSearchRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/devlog/$slug': typeof DevlogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/devlog/': typeof DevlogIndexRoute
  '/api/og/devlog/$slug.webp': typeof ApiOgDevlogSlugDotwebpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/waitlist': typeof WaitlistRoute
  '/api/search': typeof ApiSearchRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/devlog/$slug': typeof DevlogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/blog': typeof BlogIndexRoute
  '/devlog': typeof DevlogIndexRoute
  '/api/og/devlog/$slug.webp': typeof ApiOgDevlogSlugDotwebpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/waitlist': typeof WaitlistRoute
  '/api/search': typeof ApiSearchRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/devlog/$slug': typeof DevlogSlugRoute
  '/docs/$': typeof DocsSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/devlog/': typeof DevlogIndexRoute
  '/api/og/devlog/$slug.webp': typeof ApiOgDevlogSlugDotwebpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/waitlist'
    | '/api/search'
    | '/api/waitlist'
    | '/blog/$slug'
    | '/devlog/$slug'
    | '/docs/$'
    | '/blog/'
    | '/devlog/'
    | '/api/og/devlog/$slug.webp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/waitlist'
    | '/api/search'
    | '/api/waitlist'
    | '/blog/$slug'
    | '/devlog/$slug'
    | '/docs/$'
    | '/blog'
    | '/devlog'
    | '/api/og/devlog/$slug.webp'
  id:
    | '__root__'
    | '/'
    | '/waitlist'
    | '/api/search'
    | '/api/waitlist'
    | '/blog/$slug'
    | '/devlog/$slug'
    | '/docs/$'
    | '/blog/'
    | '/devlog/'
    | '/api/og/devlog/$slug.webp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WaitlistRoute: typeof WaitlistRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiWaitlistRoute: typeof ApiWaitlistRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DevlogSlugRoute: typeof DevlogSlugRoute
  DocsSplatRoute: typeof DocsSplatRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DevlogIndexRoute: typeof DevlogIndexRoute
  ApiOgDevlogSlugDotwebpRoute: typeof ApiOgDevlogSlugDotwebpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devlog/': {
      id: '/devlog/'
      path: '/devlog'
      fullPath: '/devlog/'
      preLoaderRoute: typeof DevlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devlog/$slug': {
      id: '/devlog/$slug'
      path: '/devlog/$slug'
      fullPath: '/devlog/$slug'
      preLoaderRoute: typeof DevlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waitlist': {
      id: '/api/waitlist'
      path: '/api/waitlist'
      fullPath: '/api/waitlist'
      preLoaderRoute: typeof ApiWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/devlog/$slug.webp': {
      id: '/api/og/devlog/$slug.webp'
      path: '/api/og/devlog/$slug.webp'
      fullPath: '/api/og/devlog/$slug.webp'
      preLoaderRoute: typeof ApiOgDevlogSlugDotwebpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WaitlistRoute: WaitlistRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiWaitlistRoute: ApiWaitlistRoute,
  BlogSlugRoute: BlogSlugRoute,
  DevlogSlugRoute: DevlogSlugRoute,
  DocsSplatRoute: DocsSplatRoute,
  BlogIndexRoute: BlogIndexRoute,
  DevlogIndexRoute: DevlogIndexRoute,
  ApiOgDevlogSlugDotwebpRoute: ApiOgDevlogSlugDotwebpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
