/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as WebhookGithubRouteImport } from './routes/webhook/github'
import { Route as CliDeviceRouteImport } from './routes/cli/device'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/_dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/_dashboard/index'
import { Route as ApiEventsSubscribeRouteImport } from './routes/api/events/subscribe'
import { Route as ApiCliTestHistoryRouteImport } from './routes/api/cli/test-history'
import { Route as ApiCliSlowestTestsRouteImport } from './routes/api/cli/slowest-tests'
import { Route as ApiCliSlowestJobsRouteImport } from './routes/api/cli/slowest-jobs'
import { Route as ApiCliRunsRouteImport } from './routes/api/cli/runs'
import { Route as ApiCliGrepRouteImport } from './routes/api/cli/grep'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as AuthenticatedDashboardUsersManagementRouteImport } from './routes/_authenticated/_dashboard/users-management'
import { Route as AuthenticatedDashboardTestsOverviewRouteImport } from './routes/_authenticated/_dashboard/tests-overview'
import { Route as AuthenticatedDashboardRunsRouteImport } from './routes/_authenticated/_dashboard/runs'
import { Route as AuthenticatedDashboardReposRouteImport } from './routes/_authenticated/_dashboard/repos'
import { Route as AuthenticatedDashboardCostAnalysisRouteImport } from './routes/_authenticated/_dashboard/cost-analysis'
import { Route as AuthenticatedDashboardAccountRouteImport } from './routes/_authenticated/_dashboard/account'
import { Route as AuthenticatedDashboardWorkflowsIndexRouteImport } from './routes/_authenticated/_dashboard/workflows/index'
import { Route as AuthenticatedDashboardRunsIndexRouteImport } from './routes/_authenticated/_dashboard/runs/index'
import { Route as ApiGithubInstallStartRouteImport } from './routes/api/github/install/start'
import { Route as ApiGithubInstallCallbackRouteImport } from './routes/api/github/install/callback'
import { Route as ApiCliRunsWatchRouteImport } from './routes/api/cli/runs/watch'
import { Route as ApiCliRunsStatusRouteImport } from './routes/api/cli/runs/status'
import { Route as ApiCliRunsTraceIdRouteImport } from './routes/api/cli/runs/$traceId'
import { Route as ApiCliNotifierFailuresRouteImport } from './routes/api/cli/notifier/failures'
import { Route as AuthenticatedDashboardRunsTraceIdRouteRouteImport } from './routes/_authenticated/_dashboard/runs/$traceId/route'
import { Route as AuthenticatedDashboardRunsTraceIdIndexRouteImport } from './routes/_authenticated/_dashboard/runs/$traceId/index'
import { Route as ApiCliRunsTraceIdLogsRouteImport } from './routes/api/cli/runs/$traceId/logs'
import { Route as ApiCliAuthDeviceStartRouteImport } from './routes/api/cli/auth/device/start'
import { Route as ApiCliAuthDevicePollRouteImport } from './routes/api/cli/auth/device/poll'
import { Route as ApiCliAuthDeviceApproveRouteImport } from './routes/api/cli/auth/device/approve'
import { Route as AuthenticatedDashboardWorkflowsRepoWorkflowNameRouteImport } from './routes/_authenticated/_dashboard/workflows/$repo/$workflowName'
import { Route as AuthenticatedDashboardRunsTraceIdTraceRouteImport } from './routes/_authenticated/_dashboard/runs/$traceId/trace'
import { Route as AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRouteImport } from './routes/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/index'
import { Route as AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRouteImport } from './routes/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhookGithubRoute = WebhookGithubRouteImport.update({
  id: '/webhook/github',
  path: '/webhook/github',
  getParentRoute: () => rootRouteImport,
} as any)
const CliDeviceRoute = CliDeviceRouteImport.update({
  id: '/cli/device',
  path: '/cli/device',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiEventsSubscribeRoute = ApiEventsSubscribeRouteImport.update({
  id: '/api/events/subscribe',
  path: '/api/events/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliTestHistoryRoute = ApiCliTestHistoryRouteImport.update({
  id: '/api/cli/test-history',
  path: '/api/cli/test-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliSlowestTestsRoute = ApiCliSlowestTestsRouteImport.update({
  id: '/api/cli/slowest-tests',
  path: '/api/cli/slowest-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliSlowestJobsRoute = ApiCliSlowestJobsRouteImport.update({
  id: '/api/cli/slowest-jobs',
  path: '/api/cli/slowest-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliRunsRoute = ApiCliRunsRouteImport.update({
  id: '/api/cli/runs',
  path: '/api/cli/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliGrepRoute = ApiCliGrepRouteImport.update({
  id: '/api/cli/grep',
  path: '/api/cli/grep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardUsersManagementRoute =
  AuthenticatedDashboardUsersManagementRouteImport.update({
    id: '/users-management',
    path: '/users-management',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTestsOverviewRoute =
  AuthenticatedDashboardTestsOverviewRouteImport.update({
    id: '/tests-overview',
    path: '/tests-overview',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRunsRoute =
  AuthenticatedDashboardRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReposRoute =
  AuthenticatedDashboardReposRouteImport.update({
    id: '/repos',
    path: '/repos',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCostAnalysisRoute =
  AuthenticatedDashboardCostAnalysisRouteImport.update({
    id: '/cost-analysis',
    path: '/cost-analysis',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAccountRoute =
  AuthenticatedDashboardAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardWorkflowsIndexRoute =
  AuthenticatedDashboardWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRunsIndexRoute =
  AuthenticatedDashboardRunsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRunsRoute,
  } as any)
const ApiGithubInstallStartRoute = ApiGithubInstallStartRouteImport.update({
  id: '/api/github/install/start',
  path: '/api/github/install/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallCallbackRoute =
  ApiGithubInstallCallbackRouteImport.update({
    id: '/api/github/install/callback',
    path: '/api/github/install/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCliRunsWatchRoute = ApiCliRunsWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => ApiCliRunsRoute,
} as any)
const ApiCliRunsStatusRoute = ApiCliRunsStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiCliRunsRoute,
} as any)
const ApiCliRunsTraceIdRoute = ApiCliRunsTraceIdRouteImport.update({
  id: '/$traceId',
  path: '/$traceId',
  getParentRoute: () => ApiCliRunsRoute,
} as any)
const ApiCliNotifierFailuresRoute = ApiCliNotifierFailuresRouteImport.update({
  id: '/api/cli/notifier/failures',
  path: '/api/cli/notifier/failures',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRunsTraceIdRouteRoute =
  AuthenticatedDashboardRunsTraceIdRouteRouteImport.update({
    id: '/$traceId',
    path: '/$traceId',
    getParentRoute: () => AuthenticatedDashboardRunsRoute,
  } as any)
const AuthenticatedDashboardRunsTraceIdIndexRoute =
  AuthenticatedDashboardRunsTraceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRunsTraceIdRouteRoute,
  } as any)
const ApiCliRunsTraceIdLogsRoute = ApiCliRunsTraceIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ApiCliRunsTraceIdRoute,
} as any)
const ApiCliAuthDeviceStartRoute = ApiCliAuthDeviceStartRouteImport.update({
  id: '/api/cli/auth/device/start',
  path: '/api/cli/auth/device/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliAuthDevicePollRoute = ApiCliAuthDevicePollRouteImport.update({
  id: '/api/cli/auth/device/poll',
  path: '/api/cli/auth/device/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliAuthDeviceApproveRoute = ApiCliAuthDeviceApproveRouteImport.update({
  id: '/api/cli/auth/device/approve',
  path: '/api/cli/auth/device/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardWorkflowsRepoWorkflowNameRoute =
  AuthenticatedDashboardWorkflowsRepoWorkflowNameRouteImport.update({
    id: '/workflows/$repo/$workflowName',
    path: '/workflows/$repo/$workflowName',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRunsTraceIdTraceRoute =
  AuthenticatedDashboardRunsTraceIdTraceRouteImport.update({
    id: '/trace',
    path: '/trace',
    getParentRoute: () => AuthenticatedDashboardRunsTraceIdRouteRoute,
  } as any)
const AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRoute =
  AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRouteImport.update({
    id: '/jobs/$jobId/',
    path: '/jobs/$jobId/',
    getParentRoute: () => AuthenticatedDashboardRunsTraceIdRouteRoute,
  } as any)
const AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRoute =
  AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRouteImport.update({
    id: '/jobs/$jobId/steps/$stepNumber',
    path: '/jobs/$jobId/steps/$stepNumber',
    getParentRoute: () => AuthenticatedDashboardRunsTraceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedDashboardIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/api/health': typeof ApiHealthRoute
  '/cli/device': typeof CliDeviceRoute
  '/webhook/github': typeof WebhookGithubRoute
  '/account': typeof AuthenticatedDashboardAccountRoute
  '/cost-analysis': typeof AuthenticatedDashboardCostAnalysisRoute
  '/repos': typeof AuthenticatedDashboardReposRoute
  '/runs': typeof AuthenticatedDashboardRunsRouteWithChildren
  '/tests-overview': typeof AuthenticatedDashboardTestsOverviewRoute
  '/users-management': typeof AuthenticatedDashboardUsersManagementRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/cli/grep': typeof ApiCliGrepRoute
  '/api/cli/runs': typeof ApiCliRunsRouteWithChildren
  '/api/cli/slowest-jobs': typeof ApiCliSlowestJobsRoute
  '/api/cli/slowest-tests': typeof ApiCliSlowestTestsRoute
  '/api/cli/test-history': typeof ApiCliTestHistoryRoute
  '/api/events/subscribe': typeof ApiEventsSubscribeRoute
  '/runs/$traceId': typeof AuthenticatedDashboardRunsTraceIdRouteRouteWithChildren
  '/api/cli/notifier/failures': typeof ApiCliNotifierFailuresRoute
  '/api/cli/runs/$traceId': typeof ApiCliRunsTraceIdRouteWithChildren
  '/api/cli/runs/status': typeof ApiCliRunsStatusRoute
  '/api/cli/runs/watch': typeof ApiCliRunsWatchRoute
  '/api/github/install/callback': typeof ApiGithubInstallCallbackRoute
  '/api/github/install/start': typeof ApiGithubInstallStartRoute
  '/runs/': typeof AuthenticatedDashboardRunsIndexRoute
  '/workflows/': typeof AuthenticatedDashboardWorkflowsIndexRoute
  '/runs/$traceId/trace': typeof AuthenticatedDashboardRunsTraceIdTraceRoute
  '/workflows/$repo/$workflowName': typeof AuthenticatedDashboardWorkflowsRepoWorkflowNameRoute
  '/api/cli/auth/device/approve': typeof ApiCliAuthDeviceApproveRoute
  '/api/cli/auth/device/poll': typeof ApiCliAuthDevicePollRoute
  '/api/cli/auth/device/start': typeof ApiCliAuthDeviceStartRoute
  '/api/cli/runs/$traceId/logs': typeof ApiCliRunsTraceIdLogsRoute
  '/runs/$traceId/': typeof AuthenticatedDashboardRunsTraceIdIndexRoute
  '/runs/$traceId/jobs/$jobId/': typeof AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRoute
  '/runs/$traceId/jobs/$jobId/steps/$stepNumber': typeof AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedDashboardIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/api/health': typeof ApiHealthRoute
  '/cli/device': typeof CliDeviceRoute
  '/webhook/github': typeof WebhookGithubRoute
  '/account': typeof AuthenticatedDashboardAccountRoute
  '/cost-analysis': typeof AuthenticatedDashboardCostAnalysisRoute
  '/repos': typeof AuthenticatedDashboardReposRoute
  '/tests-overview': typeof AuthenticatedDashboardTestsOverviewRoute
  '/users-management': typeof AuthenticatedDashboardUsersManagementRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/cli/grep': typeof ApiCliGrepRoute
  '/api/cli/runs': typeof ApiCliRunsRouteWithChildren
  '/api/cli/slowest-jobs': typeof ApiCliSlowestJobsRoute
  '/api/cli/slowest-tests': typeof ApiCliSlowestTestsRoute
  '/api/cli/test-history': typeof ApiCliTestHistoryRoute
  '/api/events/subscribe': typeof ApiEventsSubscribeRoute
  '/api/cli/notifier/failures': typeof ApiCliNotifierFailuresRoute
  '/api/cli/runs/$traceId': typeof ApiCliRunsTraceIdRouteWithChildren
  '/api/cli/runs/status': typeof ApiCliRunsStatusRoute
  '/api/cli/runs/watch': typeof ApiCliRunsWatchRoute
  '/api/github/install/callback': typeof ApiGithubInstallCallbackRoute
  '/api/github/install/start': typeof ApiGithubInstallStartRoute
  '/runs': typeof AuthenticatedDashboardRunsIndexRoute
  '/workflows': typeof AuthenticatedDashboardWorkflowsIndexRoute
  '/runs/$traceId/trace': typeof AuthenticatedDashboardRunsTraceIdTraceRoute
  '/workflows/$repo/$workflowName': typeof AuthenticatedDashboardWorkflowsRepoWorkflowNameRoute
  '/api/cli/auth/device/approve': typeof ApiCliAuthDeviceApproveRoute
  '/api/cli/auth/device/poll': typeof ApiCliAuthDevicePollRoute
  '/api/cli/auth/device/start': typeof ApiCliAuthDeviceStartRoute
  '/api/cli/runs/$traceId/logs': typeof ApiCliRunsTraceIdLogsRoute
  '/runs/$traceId': typeof AuthenticatedDashboardRunsTraceIdIndexRoute
  '/runs/$traceId/jobs/$jobId': typeof AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRoute
  '/runs/$traceId/jobs/$jobId/steps/$stepNumber': typeof AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/_dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/cli/device': typeof CliDeviceRoute
  '/webhook/github': typeof WebhookGithubRoute
  '/_authenticated/_dashboard/account': typeof AuthenticatedDashboardAccountRoute
  '/_authenticated/_dashboard/cost-analysis': typeof AuthenticatedDashboardCostAnalysisRoute
  '/_authenticated/_dashboard/repos': typeof AuthenticatedDashboardReposRoute
  '/_authenticated/_dashboard/runs': typeof AuthenticatedDashboardRunsRouteWithChildren
  '/_authenticated/_dashboard/tests-overview': typeof AuthenticatedDashboardTestsOverviewRoute
  '/_authenticated/_dashboard/users-management': typeof AuthenticatedDashboardUsersManagementRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/cli/grep': typeof ApiCliGrepRoute
  '/api/cli/runs': typeof ApiCliRunsRouteWithChildren
  '/api/cli/slowest-jobs': typeof ApiCliSlowestJobsRoute
  '/api/cli/slowest-tests': typeof ApiCliSlowestTestsRoute
  '/api/cli/test-history': typeof ApiCliTestHistoryRoute
  '/api/events/subscribe': typeof ApiEventsSubscribeRoute
  '/_authenticated/_dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/_dashboard/runs/$traceId': typeof AuthenticatedDashboardRunsTraceIdRouteRouteWithChildren
  '/api/cli/notifier/failures': typeof ApiCliNotifierFailuresRoute
  '/api/cli/runs/$traceId': typeof ApiCliRunsTraceIdRouteWithChildren
  '/api/cli/runs/status': typeof ApiCliRunsStatusRoute
  '/api/cli/runs/watch': typeof ApiCliRunsWatchRoute
  '/api/github/install/callback': typeof ApiGithubInstallCallbackRoute
  '/api/github/install/start': typeof ApiGithubInstallStartRoute
  '/_authenticated/_dashboard/runs/': typeof AuthenticatedDashboardRunsIndexRoute
  '/_authenticated/_dashboard/workflows/': typeof AuthenticatedDashboardWorkflowsIndexRoute
  '/_authenticated/_dashboard/runs/$traceId/trace': typeof AuthenticatedDashboardRunsTraceIdTraceRoute
  '/_authenticated/_dashboard/workflows/$repo/$workflowName': typeof AuthenticatedDashboardWorkflowsRepoWorkflowNameRoute
  '/api/cli/auth/device/approve': typeof ApiCliAuthDeviceApproveRoute
  '/api/cli/auth/device/poll': typeof ApiCliAuthDevicePollRoute
  '/api/cli/auth/device/start': typeof ApiCliAuthDeviceStartRoute
  '/api/cli/runs/$traceId/logs': typeof ApiCliRunsTraceIdLogsRoute
  '/_authenticated/_dashboard/runs/$traceId/': typeof AuthenticatedDashboardRunsTraceIdIndexRoute
  '/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/': typeof AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRoute
  '/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber': typeof AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/api/health'
    | '/cli/device'
    | '/webhook/github'
    | '/account'
    | '/cost-analysis'
    | '/repos'
    | '/runs'
    | '/tests-overview'
    | '/users-management'
    | '/api/auth/callback'
    | '/api/cli/grep'
    | '/api/cli/runs'
    | '/api/cli/slowest-jobs'
    | '/api/cli/slowest-tests'
    | '/api/cli/test-history'
    | '/api/events/subscribe'
    | '/runs/$traceId'
    | '/api/cli/notifier/failures'
    | '/api/cli/runs/$traceId'
    | '/api/cli/runs/status'
    | '/api/cli/runs/watch'
    | '/api/github/install/callback'
    | '/api/github/install/start'
    | '/runs/'
    | '/workflows/'
    | '/runs/$traceId/trace'
    | '/workflows/$repo/$workflowName'
    | '/api/cli/auth/device/approve'
    | '/api/cli/auth/device/poll'
    | '/api/cli/auth/device/start'
    | '/api/cli/runs/$traceId/logs'
    | '/runs/$traceId/'
    | '/runs/$traceId/jobs/$jobId/'
    | '/runs/$traceId/jobs/$jobId/steps/$stepNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/api/health'
    | '/cli/device'
    | '/webhook/github'
    | '/account'
    | '/cost-analysis'
    | '/repos'
    | '/tests-overview'
    | '/users-management'
    | '/api/auth/callback'
    | '/api/cli/grep'
    | '/api/cli/runs'
    | '/api/cli/slowest-jobs'
    | '/api/cli/slowest-tests'
    | '/api/cli/test-history'
    | '/api/events/subscribe'
    | '/api/cli/notifier/failures'
    | '/api/cli/runs/$traceId'
    | '/api/cli/runs/status'
    | '/api/cli/runs/watch'
    | '/api/github/install/callback'
    | '/api/github/install/start'
    | '/runs'
    | '/workflows'
    | '/runs/$traceId/trace'
    | '/workflows/$repo/$workflowName'
    | '/api/cli/auth/device/approve'
    | '/api/cli/auth/device/poll'
    | '/api/cli/auth/device/start'
    | '/api/cli/runs/$traceId/logs'
    | '/runs/$traceId'
    | '/runs/$traceId/jobs/$jobId'
    | '/runs/$traceId/jobs/$jobId/steps/$stepNumber'
  id:
    | '__root__'
    | '/_authenticated'
    | '/onboarding'
    | '/_authenticated/_dashboard'
    | '/api/health'
    | '/cli/device'
    | '/webhook/github'
    | '/_authenticated/_dashboard/account'
    | '/_authenticated/_dashboard/cost-analysis'
    | '/_authenticated/_dashboard/repos'
    | '/_authenticated/_dashboard/runs'
    | '/_authenticated/_dashboard/tests-overview'
    | '/_authenticated/_dashboard/users-management'
    | '/api/auth/callback'
    | '/api/cli/grep'
    | '/api/cli/runs'
    | '/api/cli/slowest-jobs'
    | '/api/cli/slowest-tests'
    | '/api/cli/test-history'
    | '/api/events/subscribe'
    | '/_authenticated/_dashboard/'
    | '/_authenticated/_dashboard/runs/$traceId'
    | '/api/cli/notifier/failures'
    | '/api/cli/runs/$traceId'
    | '/api/cli/runs/status'
    | '/api/cli/runs/watch'
    | '/api/github/install/callback'
    | '/api/github/install/start'
    | '/_authenticated/_dashboard/runs/'
    | '/_authenticated/_dashboard/workflows/'
    | '/_authenticated/_dashboard/runs/$traceId/trace'
    | '/_authenticated/_dashboard/workflows/$repo/$workflowName'
    | '/api/cli/auth/device/approve'
    | '/api/cli/auth/device/poll'
    | '/api/cli/auth/device/start'
    | '/api/cli/runs/$traceId/logs'
    | '/_authenticated/_dashboard/runs/$traceId/'
    | '/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/'
    | '/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ApiHealthRoute: typeof ApiHealthRoute
  CliDeviceRoute: typeof CliDeviceRoute
  WebhookGithubRoute: typeof WebhookGithubRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiCliGrepRoute: typeof ApiCliGrepRoute
  ApiCliRunsRoute: typeof ApiCliRunsRouteWithChildren
  ApiCliSlowestJobsRoute: typeof ApiCliSlowestJobsRoute
  ApiCliSlowestTestsRoute: typeof ApiCliSlowestTestsRoute
  ApiCliTestHistoryRoute: typeof ApiCliTestHistoryRoute
  ApiEventsSubscribeRoute: typeof ApiEventsSubscribeRoute
  ApiCliNotifierFailuresRoute: typeof ApiCliNotifierFailuresRoute
  ApiGithubInstallCallbackRoute: typeof ApiGithubInstallCallbackRoute
  ApiGithubInstallStartRoute: typeof ApiGithubInstallStartRoute
  ApiCliAuthDeviceApproveRoute: typeof ApiCliAuthDeviceApproveRoute
  ApiCliAuthDevicePollRoute: typeof ApiCliAuthDevicePollRoute
  ApiCliAuthDeviceStartRoute: typeof ApiCliAuthDeviceStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhook/github': {
      id: '/webhook/github'
      path: '/webhook/github'
      fullPath: '/webhook/github'
      preLoaderRoute: typeof WebhookGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/device': {
      id: '/cli/device'
      path: '/cli/device'
      fullPath: '/cli/device'
      preLoaderRoute: typeof CliDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_dashboard': {
      id: '/_authenticated/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dashboard/': {
      id: '/_authenticated/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/events/subscribe': {
      id: '/api/events/subscribe'
      path: '/api/events/subscribe'
      fullPath: '/api/events/subscribe'
      preLoaderRoute: typeof ApiEventsSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/test-history': {
      id: '/api/cli/test-history'
      path: '/api/cli/test-history'
      fullPath: '/api/cli/test-history'
      preLoaderRoute: typeof ApiCliTestHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/slowest-tests': {
      id: '/api/cli/slowest-tests'
      path: '/api/cli/slowest-tests'
      fullPath: '/api/cli/slowest-tests'
      preLoaderRoute: typeof ApiCliSlowestTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/slowest-jobs': {
      id: '/api/cli/slowest-jobs'
      path: '/api/cli/slowest-jobs'
      fullPath: '/api/cli/slowest-jobs'
      preLoaderRoute: typeof ApiCliSlowestJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/runs': {
      id: '/api/cli/runs'
      path: '/api/cli/runs'
      fullPath: '/api/cli/runs'
      preLoaderRoute: typeof ApiCliRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/grep': {
      id: '/api/cli/grep'
      path: '/api/cli/grep'
      fullPath: '/api/cli/grep'
      preLoaderRoute: typeof ApiCliGrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_dashboard/users-management': {
      id: '/_authenticated/_dashboard/users-management'
      path: '/users-management'
      fullPath: '/users-management'
      preLoaderRoute: typeof AuthenticatedDashboardUsersManagementRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/tests-overview': {
      id: '/_authenticated/_dashboard/tests-overview'
      path: '/tests-overview'
      fullPath: '/tests-overview'
      preLoaderRoute: typeof AuthenticatedDashboardTestsOverviewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/runs': {
      id: '/_authenticated/_dashboard/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof AuthenticatedDashboardRunsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/repos': {
      id: '/_authenticated/_dashboard/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof AuthenticatedDashboardReposRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/cost-analysis': {
      id: '/_authenticated/_dashboard/cost-analysis'
      path: '/cost-analysis'
      fullPath: '/cost-analysis'
      preLoaderRoute: typeof AuthenticatedDashboardCostAnalysisRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/account': {
      id: '/_authenticated/_dashboard/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedDashboardAccountRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/workflows/': {
      id: '/_authenticated/_dashboard/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AuthenticatedDashboardWorkflowsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/runs/': {
      id: '/_authenticated/_dashboard/runs/'
      path: '/'
      fullPath: '/runs/'
      preLoaderRoute: typeof AuthenticatedDashboardRunsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRunsRoute
    }
    '/api/github/install/start': {
      id: '/api/github/install/start'
      path: '/api/github/install/start'
      fullPath: '/api/github/install/start'
      preLoaderRoute: typeof ApiGithubInstallStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/install/callback': {
      id: '/api/github/install/callback'
      path: '/api/github/install/callback'
      fullPath: '/api/github/install/callback'
      preLoaderRoute: typeof ApiGithubInstallCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/runs/watch': {
      id: '/api/cli/runs/watch'
      path: '/watch'
      fullPath: '/api/cli/runs/watch'
      preLoaderRoute: typeof ApiCliRunsWatchRouteImport
      parentRoute: typeof ApiCliRunsRoute
    }
    '/api/cli/runs/status': {
      id: '/api/cli/runs/status'
      path: '/status'
      fullPath: '/api/cli/runs/status'
      preLoaderRoute: typeof ApiCliRunsStatusRouteImport
      parentRoute: typeof ApiCliRunsRoute
    }
    '/api/cli/runs/$traceId': {
      id: '/api/cli/runs/$traceId'
      path: '/$traceId'
      fullPath: '/api/cli/runs/$traceId'
      preLoaderRoute: typeof ApiCliRunsTraceIdRouteImport
      parentRoute: typeof ApiCliRunsRoute
    }
    '/api/cli/notifier/failures': {
      id: '/api/cli/notifier/failures'
      path: '/api/cli/notifier/failures'
      fullPath: '/api/cli/notifier/failures'
      preLoaderRoute: typeof ApiCliNotifierFailuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_dashboard/runs/$traceId': {
      id: '/_authenticated/_dashboard/runs/$traceId'
      path: '/$traceId'
      fullPath: '/runs/$traceId'
      preLoaderRoute: typeof AuthenticatedDashboardRunsTraceIdRouteRouteImport
      parentRoute: typeof AuthenticatedDashboardRunsRoute
    }
    '/_authenticated/_dashboard/runs/$traceId/': {
      id: '/_authenticated/_dashboard/runs/$traceId/'
      path: '/'
      fullPath: '/runs/$traceId/'
      preLoaderRoute: typeof AuthenticatedDashboardRunsTraceIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRunsTraceIdRouteRoute
    }
    '/api/cli/runs/$traceId/logs': {
      id: '/api/cli/runs/$traceId/logs'
      path: '/logs'
      fullPath: '/api/cli/runs/$traceId/logs'
      preLoaderRoute: typeof ApiCliRunsTraceIdLogsRouteImport
      parentRoute: typeof ApiCliRunsTraceIdRoute
    }
    '/api/cli/auth/device/start': {
      id: '/api/cli/auth/device/start'
      path: '/api/cli/auth/device/start'
      fullPath: '/api/cli/auth/device/start'
      preLoaderRoute: typeof ApiCliAuthDeviceStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/auth/device/poll': {
      id: '/api/cli/auth/device/poll'
      path: '/api/cli/auth/device/poll'
      fullPath: '/api/cli/auth/device/poll'
      preLoaderRoute: typeof ApiCliAuthDevicePollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/auth/device/approve': {
      id: '/api/cli/auth/device/approve'
      path: '/api/cli/auth/device/approve'
      fullPath: '/api/cli/auth/device/approve'
      preLoaderRoute: typeof ApiCliAuthDeviceApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_dashboard/workflows/$repo/$workflowName': {
      id: '/_authenticated/_dashboard/workflows/$repo/$workflowName'
      path: '/workflows/$repo/$workflowName'
      fullPath: '/workflows/$repo/$workflowName'
      preLoaderRoute: typeof AuthenticatedDashboardWorkflowsRepoWorkflowNameRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/runs/$traceId/trace': {
      id: '/_authenticated/_dashboard/runs/$traceId/trace'
      path: '/trace'
      fullPath: '/runs/$traceId/trace'
      preLoaderRoute: typeof AuthenticatedDashboardRunsTraceIdTraceRouteImport
      parentRoute: typeof AuthenticatedDashboardRunsTraceIdRouteRoute
    }
    '/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/': {
      id: '/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/'
      path: '/jobs/$jobId'
      fullPath: '/runs/$traceId/jobs/$jobId/'
      preLoaderRoute: typeof AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRunsTraceIdRouteRoute
    }
    '/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber': {
      id: '/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber'
      path: '/jobs/$jobId/steps/$stepNumber'
      fullPath: '/runs/$traceId/jobs/$jobId/steps/$stepNumber'
      preLoaderRoute: typeof AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRouteImport
      parentRoute: typeof AuthenticatedDashboardRunsTraceIdRouteRoute
    }
  }
}

interface AuthenticatedDashboardRunsTraceIdRouteRouteChildren {
  AuthenticatedDashboardRunsTraceIdTraceRoute: typeof AuthenticatedDashboardRunsTraceIdTraceRoute
  AuthenticatedDashboardRunsTraceIdIndexRoute: typeof AuthenticatedDashboardRunsTraceIdIndexRoute
  AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRoute: typeof AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRoute
  AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRoute: typeof AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRoute
}

const AuthenticatedDashboardRunsTraceIdRouteRouteChildren: AuthenticatedDashboardRunsTraceIdRouteRouteChildren =
  {
    AuthenticatedDashboardRunsTraceIdTraceRoute:
      AuthenticatedDashboardRunsTraceIdTraceRoute,
    AuthenticatedDashboardRunsTraceIdIndexRoute:
      AuthenticatedDashboardRunsTraceIdIndexRoute,
    AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRoute:
      AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRoute,
    AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRoute:
      AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRoute,
  }

const AuthenticatedDashboardRunsTraceIdRouteRouteWithChildren =
  AuthenticatedDashboardRunsTraceIdRouteRoute._addFileChildren(
    AuthenticatedDashboardRunsTraceIdRouteRouteChildren,
  )

interface AuthenticatedDashboardRunsRouteChildren {
  AuthenticatedDashboardRunsTraceIdRouteRoute: typeof AuthenticatedDashboardRunsTraceIdRouteRouteWithChildren
  AuthenticatedDashboardRunsIndexRoute: typeof AuthenticatedDashboardRunsIndexRoute
}

const AuthenticatedDashboardRunsRouteChildren: AuthenticatedDashboardRunsRouteChildren =
  {
    AuthenticatedDashboardRunsTraceIdRouteRoute:
      AuthenticatedDashboardRunsTraceIdRouteRouteWithChildren,
    AuthenticatedDashboardRunsIndexRoute: AuthenticatedDashboardRunsIndexRoute,
  }

const AuthenticatedDashboardRunsRouteWithChildren =
  AuthenticatedDashboardRunsRoute._addFileChildren(
    AuthenticatedDashboardRunsRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAccountRoute: typeof AuthenticatedDashboardAccountRoute
  AuthenticatedDashboardCostAnalysisRoute: typeof AuthenticatedDashboardCostAnalysisRoute
  AuthenticatedDashboardReposRoute: typeof AuthenticatedDashboardReposRoute
  AuthenticatedDashboardRunsRoute: typeof AuthenticatedDashboardRunsRouteWithChildren
  AuthenticatedDashboardTestsOverviewRoute: typeof AuthenticatedDashboardTestsOverviewRoute
  AuthenticatedDashboardUsersManagementRoute: typeof AuthenticatedDashboardUsersManagementRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardWorkflowsIndexRoute: typeof AuthenticatedDashboardWorkflowsIndexRoute
  AuthenticatedDashboardWorkflowsRepoWorkflowNameRoute: typeof AuthenticatedDashboardWorkflowsRepoWorkflowNameRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAccountRoute: AuthenticatedDashboardAccountRoute,
    AuthenticatedDashboardCostAnalysisRoute:
      AuthenticatedDashboardCostAnalysisRoute,
    AuthenticatedDashboardReposRoute: AuthenticatedDashboardReposRoute,
    AuthenticatedDashboardRunsRoute:
      AuthenticatedDashboardRunsRouteWithChildren,
    AuthenticatedDashboardTestsOverviewRoute:
      AuthenticatedDashboardTestsOverviewRoute,
    AuthenticatedDashboardUsersManagementRoute:
      AuthenticatedDashboardUsersManagementRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardWorkflowsIndexRoute:
      AuthenticatedDashboardWorkflowsIndexRoute,
    AuthenticatedDashboardWorkflowsRepoWorkflowNameRoute:
      AuthenticatedDashboardWorkflowsRepoWorkflowNameRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiCliRunsTraceIdRouteChildren {
  ApiCliRunsTraceIdLogsRoute: typeof ApiCliRunsTraceIdLogsRoute
}

const ApiCliRunsTraceIdRouteChildren: ApiCliRunsTraceIdRouteChildren = {
  ApiCliRunsTraceIdLogsRoute: ApiCliRunsTraceIdLogsRoute,
}

const ApiCliRunsTraceIdRouteWithChildren =
  ApiCliRunsTraceIdRoute._addFileChildren(ApiCliRunsTraceIdRouteChildren)

interface ApiCliRunsRouteChildren {
  ApiCliRunsTraceIdRoute: typeof ApiCliRunsTraceIdRouteWithChildren
  ApiCliRunsStatusRoute: typeof ApiCliRunsStatusRoute
  ApiCliRunsWatchRoute: typeof ApiCliRunsWatchRoute
}

const ApiCliRunsRouteChildren: ApiCliRunsRouteChildren = {
  ApiCliRunsTraceIdRoute: ApiCliRunsTraceIdRouteWithChildren,
  ApiCliRunsStatusRoute: ApiCliRunsStatusRoute,
  ApiCliRunsWatchRoute: ApiCliRunsWatchRoute,
}

const ApiCliRunsRouteWithChildren = ApiCliRunsRoute._addFileChildren(
  ApiCliRunsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ApiHealthRoute: ApiHealthRoute,
  CliDeviceRoute: CliDeviceRoute,
  WebhookGithubRoute: WebhookGithubRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiCliGrepRoute: ApiCliGrepRoute,
  ApiCliRunsRoute: ApiCliRunsRouteWithChildren,
  ApiCliSlowestJobsRoute: ApiCliSlowestJobsRoute,
  ApiCliSlowestTestsRoute: ApiCliSlowestTestsRoute,
  ApiCliTestHistoryRoute: ApiCliTestHistoryRoute,
  ApiEventsSubscribeRoute: ApiEventsSubscribeRoute,
  ApiCliNotifierFailuresRoute: ApiCliNotifierFailuresRoute,
  ApiGithubInstallCallbackRoute: ApiGithubInstallCallbackRoute,
  ApiGithubInstallStartRoute: ApiGithubInstallStartRoute,
  ApiCliAuthDeviceApproveRoute: ApiCliAuthDeviceApproveRoute,
  ApiCliAuthDevicePollRoute: ApiCliAuthDevicePollRoute,
  ApiCliAuthDeviceStartRoute: ApiCliAuthDeviceStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
