/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTestResultsRouteImport } from './routes/dashboard/test-results'
import { Route as DashboardRunsRouteImport } from './routes/dashboard/runs'
import { Route as DashboardReposRouteImport } from './routes/dashboard/repos'
import { Route as DashboardFlakyTestsRouteImport } from './routes/dashboard/flaky-tests'
import { Route as DashboardFailuresRouteImport } from './routes/dashboard/failures'
import { Route as DashboardCostAnalysisRouteImport } from './routes/dashboard/cost-analysis'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as DashboardWorkflowsIndexRouteImport } from './routes/dashboard/workflows/index'
import { Route as DashboardRunsIndexRouteImport } from './routes/dashboard/runs/index'
import { Route as DashboardFlakyTestsIndexRouteImport } from './routes/dashboard/flaky-tests/index'
import { Route as DashboardFlakyTestsDetailRouteImport } from './routes/dashboard/flaky-tests/detail'
import { Route as DashboardRunsTraceIdRouteRouteImport } from './routes/dashboard/runs/$traceId/route'
import { Route as DashboardRunsTraceIdIndexRouteImport } from './routes/dashboard/runs/$traceId/index'
import { Route as DashboardWorkflowsRepoWorkflowNameRouteImport } from './routes/dashboard/workflows/$repo/$workflowName'
import { Route as DashboardRunsTraceIdTraceRouteImport } from './routes/dashboard/runs/$traceId/trace'
import { Route as DashboardRunsTraceIdJobsJobIdIndexRouteImport } from './routes/dashboard/runs/$traceId/jobs/$jobId/index'
import { Route as DashboardRunsTraceIdJobsJobIdStepsStepNumberRouteImport } from './routes/dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTestResultsRoute = DashboardTestResultsRouteImport.update({
  id: '/test-results',
  path: '/test-results',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRunsRoute = DashboardRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReposRoute = DashboardReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFlakyTestsRoute = DashboardFlakyTestsRouteImport.update({
  id: '/flaky-tests',
  path: '/flaky-tests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFailuresRoute = DashboardFailuresRouteImport.update({
  id: '/failures',
  path: '/failures',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCostAnalysisRoute = DashboardCostAnalysisRouteImport.update({
  id: '/cost-analysis',
  path: '/cost-analysis',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkflowsIndexRoute = DashboardWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRunsIndexRoute = DashboardRunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRunsRoute,
} as any)
const DashboardFlakyTestsIndexRoute =
  DashboardFlakyTestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardFlakyTestsRoute,
  } as any)
const DashboardFlakyTestsDetailRoute =
  DashboardFlakyTestsDetailRouteImport.update({
    id: '/detail',
    path: '/detail',
    getParentRoute: () => DashboardFlakyTestsRoute,
  } as any)
const DashboardRunsTraceIdRouteRoute =
  DashboardRunsTraceIdRouteRouteImport.update({
    id: '/$traceId',
    path: '/$traceId',
    getParentRoute: () => DashboardRunsRoute,
  } as any)
const DashboardRunsTraceIdIndexRoute =
  DashboardRunsTraceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardRunsTraceIdRouteRoute,
  } as any)
const DashboardWorkflowsRepoWorkflowNameRoute =
  DashboardWorkflowsRepoWorkflowNameRouteImport.update({
    id: '/workflows/$repo/$workflowName',
    path: '/workflows/$repo/$workflowName',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardRunsTraceIdTraceRoute =
  DashboardRunsTraceIdTraceRouteImport.update({
    id: '/trace',
    path: '/trace',
    getParentRoute: () => DashboardRunsTraceIdRouteRoute,
  } as any)
const DashboardRunsTraceIdJobsJobIdIndexRoute =
  DashboardRunsTraceIdJobsJobIdIndexRouteImport.update({
    id: '/jobs/$jobId/',
    path: '/jobs/$jobId/',
    getParentRoute: () => DashboardRunsTraceIdRouteRoute,
  } as any)
const DashboardRunsTraceIdJobsJobIdStepsStepNumberRoute =
  DashboardRunsTraceIdJobsJobIdStepsStepNumberRouteImport.update({
    id: '/jobs/$jobId/steps/$stepNumber',
    path: '/jobs/$jobId/steps/$stepNumber',
    getParentRoute: () => DashboardRunsTraceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/mcp': typeof ApiMcpRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/cost-analysis': typeof DashboardCostAnalysisRoute
  '/dashboard/failures': typeof DashboardFailuresRoute
  '/dashboard/flaky-tests': typeof DashboardFlakyTestsRouteWithChildren
  '/dashboard/repos': typeof DashboardReposRoute
  '/dashboard/runs': typeof DashboardRunsRouteWithChildren
  '/dashboard/test-results': typeof DashboardTestResultsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/runs/$traceId': typeof DashboardRunsTraceIdRouteRouteWithChildren
  '/dashboard/flaky-tests/detail': typeof DashboardFlakyTestsDetailRoute
  '/dashboard/flaky-tests/': typeof DashboardFlakyTestsIndexRoute
  '/dashboard/runs/': typeof DashboardRunsIndexRoute
  '/dashboard/workflows/': typeof DashboardWorkflowsIndexRoute
  '/dashboard/runs/$traceId/trace': typeof DashboardRunsTraceIdTraceRoute
  '/dashboard/workflows/$repo/$workflowName': typeof DashboardWorkflowsRepoWorkflowNameRoute
  '/dashboard/runs/$traceId/': typeof DashboardRunsTraceIdIndexRoute
  '/dashboard/runs/$traceId/jobs/$jobId/': typeof DashboardRunsTraceIdJobsJobIdIndexRoute
  '/dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber': typeof DashboardRunsTraceIdJobsJobIdStepsStepNumberRoute
}
export interface FileRoutesByTo {
  '/api/mcp': typeof ApiMcpRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/cost-analysis': typeof DashboardCostAnalysisRoute
  '/dashboard/failures': typeof DashboardFailuresRoute
  '/dashboard/repos': typeof DashboardReposRoute
  '/dashboard/test-results': typeof DashboardTestResultsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/flaky-tests/detail': typeof DashboardFlakyTestsDetailRoute
  '/dashboard/flaky-tests': typeof DashboardFlakyTestsIndexRoute
  '/dashboard/runs': typeof DashboardRunsIndexRoute
  '/dashboard/workflows': typeof DashboardWorkflowsIndexRoute
  '/dashboard/runs/$traceId/trace': typeof DashboardRunsTraceIdTraceRoute
  '/dashboard/workflows/$repo/$workflowName': typeof DashboardWorkflowsRepoWorkflowNameRoute
  '/dashboard/runs/$traceId': typeof DashboardRunsTraceIdIndexRoute
  '/dashboard/runs/$traceId/jobs/$jobId': typeof DashboardRunsTraceIdJobsJobIdIndexRoute
  '/dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber': typeof DashboardRunsTraceIdJobsJobIdStepsStepNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/mcp': typeof ApiMcpRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/cost-analysis': typeof DashboardCostAnalysisRoute
  '/dashboard/failures': typeof DashboardFailuresRoute
  '/dashboard/flaky-tests': typeof DashboardFlakyTestsRouteWithChildren
  '/dashboard/repos': typeof DashboardReposRoute
  '/dashboard/runs': typeof DashboardRunsRouteWithChildren
  '/dashboard/test-results': typeof DashboardTestResultsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/runs/$traceId': typeof DashboardRunsTraceIdRouteRouteWithChildren
  '/dashboard/flaky-tests/detail': typeof DashboardFlakyTestsDetailRoute
  '/dashboard/flaky-tests/': typeof DashboardFlakyTestsIndexRoute
  '/dashboard/runs/': typeof DashboardRunsIndexRoute
  '/dashboard/workflows/': typeof DashboardWorkflowsIndexRoute
  '/dashboard/runs/$traceId/trace': typeof DashboardRunsTraceIdTraceRoute
  '/dashboard/workflows/$repo/$workflowName': typeof DashboardWorkflowsRepoWorkflowNameRoute
  '/dashboard/runs/$traceId/': typeof DashboardRunsTraceIdIndexRoute
  '/dashboard/runs/$traceId/jobs/$jobId/': typeof DashboardRunsTraceIdJobsJobIdIndexRoute
  '/dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber': typeof DashboardRunsTraceIdJobsJobIdStepsStepNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/api/mcp'
    | '/dashboard/analytics'
    | '/dashboard/cost-analysis'
    | '/dashboard/failures'
    | '/dashboard/flaky-tests'
    | '/dashboard/repos'
    | '/dashboard/runs'
    | '/dashboard/test-results'
    | '/dashboard/'
    | '/dashboard/runs/$traceId'
    | '/dashboard/flaky-tests/detail'
    | '/dashboard/flaky-tests/'
    | '/dashboard/runs/'
    | '/dashboard/workflows/'
    | '/dashboard/runs/$traceId/trace'
    | '/dashboard/workflows/$repo/$workflowName'
    | '/dashboard/runs/$traceId/'
    | '/dashboard/runs/$traceId/jobs/$jobId/'
    | '/dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/mcp'
    | '/dashboard/analytics'
    | '/dashboard/cost-analysis'
    | '/dashboard/failures'
    | '/dashboard/repos'
    | '/dashboard/test-results'
    | '/dashboard'
    | '/dashboard/flaky-tests/detail'
    | '/dashboard/flaky-tests'
    | '/dashboard/runs'
    | '/dashboard/workflows'
    | '/dashboard/runs/$traceId/trace'
    | '/dashboard/workflows/$repo/$workflowName'
    | '/dashboard/runs/$traceId'
    | '/dashboard/runs/$traceId/jobs/$jobId'
    | '/dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber'
  id:
    | '__root__'
    | '/dashboard'
    | '/api/mcp'
    | '/dashboard/analytics'
    | '/dashboard/cost-analysis'
    | '/dashboard/failures'
    | '/dashboard/flaky-tests'
    | '/dashboard/repos'
    | '/dashboard/runs'
    | '/dashboard/test-results'
    | '/dashboard/'
    | '/dashboard/runs/$traceId'
    | '/dashboard/flaky-tests/detail'
    | '/dashboard/flaky-tests/'
    | '/dashboard/runs/'
    | '/dashboard/workflows/'
    | '/dashboard/runs/$traceId/trace'
    | '/dashboard/workflows/$repo/$workflowName'
    | '/dashboard/runs/$traceId/'
    | '/dashboard/runs/$traceId/jobs/$jobId/'
    | '/dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiMcpRoute: typeof ApiMcpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/test-results': {
      id: '/dashboard/test-results'
      path: '/test-results'
      fullPath: '/dashboard/test-results'
      preLoaderRoute: typeof DashboardTestResultsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/runs': {
      id: '/dashboard/runs'
      path: '/runs'
      fullPath: '/dashboard/runs'
      preLoaderRoute: typeof DashboardRunsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/repos': {
      id: '/dashboard/repos'
      path: '/repos'
      fullPath: '/dashboard/repos'
      preLoaderRoute: typeof DashboardReposRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/flaky-tests': {
      id: '/dashboard/flaky-tests'
      path: '/flaky-tests'
      fullPath: '/dashboard/flaky-tests'
      preLoaderRoute: typeof DashboardFlakyTestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/failures': {
      id: '/dashboard/failures'
      path: '/failures'
      fullPath: '/dashboard/failures'
      preLoaderRoute: typeof DashboardFailuresRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cost-analysis': {
      id: '/dashboard/cost-analysis'
      path: '/cost-analysis'
      fullPath: '/dashboard/cost-analysis'
      preLoaderRoute: typeof DashboardCostAnalysisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workflows/': {
      id: '/dashboard/workflows/'
      path: '/workflows'
      fullPath: '/dashboard/workflows/'
      preLoaderRoute: typeof DashboardWorkflowsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/runs/': {
      id: '/dashboard/runs/'
      path: '/'
      fullPath: '/dashboard/runs/'
      preLoaderRoute: typeof DashboardRunsIndexRouteImport
      parentRoute: typeof DashboardRunsRoute
    }
    '/dashboard/flaky-tests/': {
      id: '/dashboard/flaky-tests/'
      path: '/'
      fullPath: '/dashboard/flaky-tests/'
      preLoaderRoute: typeof DashboardFlakyTestsIndexRouteImport
      parentRoute: typeof DashboardFlakyTestsRoute
    }
    '/dashboard/flaky-tests/detail': {
      id: '/dashboard/flaky-tests/detail'
      path: '/detail'
      fullPath: '/dashboard/flaky-tests/detail'
      preLoaderRoute: typeof DashboardFlakyTestsDetailRouteImport
      parentRoute: typeof DashboardFlakyTestsRoute
    }
    '/dashboard/runs/$traceId': {
      id: '/dashboard/runs/$traceId'
      path: '/$traceId'
      fullPath: '/dashboard/runs/$traceId'
      preLoaderRoute: typeof DashboardRunsTraceIdRouteRouteImport
      parentRoute: typeof DashboardRunsRoute
    }
    '/dashboard/runs/$traceId/': {
      id: '/dashboard/runs/$traceId/'
      path: '/'
      fullPath: '/dashboard/runs/$traceId/'
      preLoaderRoute: typeof DashboardRunsTraceIdIndexRouteImport
      parentRoute: typeof DashboardRunsTraceIdRouteRoute
    }
    '/dashboard/workflows/$repo/$workflowName': {
      id: '/dashboard/workflows/$repo/$workflowName'
      path: '/workflows/$repo/$workflowName'
      fullPath: '/dashboard/workflows/$repo/$workflowName'
      preLoaderRoute: typeof DashboardWorkflowsRepoWorkflowNameRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/runs/$traceId/trace': {
      id: '/dashboard/runs/$traceId/trace'
      path: '/trace'
      fullPath: '/dashboard/runs/$traceId/trace'
      preLoaderRoute: typeof DashboardRunsTraceIdTraceRouteImport
      parentRoute: typeof DashboardRunsTraceIdRouteRoute
    }
    '/dashboard/runs/$traceId/jobs/$jobId/': {
      id: '/dashboard/runs/$traceId/jobs/$jobId/'
      path: '/jobs/$jobId'
      fullPath: '/dashboard/runs/$traceId/jobs/$jobId/'
      preLoaderRoute: typeof DashboardRunsTraceIdJobsJobIdIndexRouteImport
      parentRoute: typeof DashboardRunsTraceIdRouteRoute
    }
    '/dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber': {
      id: '/dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber'
      path: '/jobs/$jobId/steps/$stepNumber'
      fullPath: '/dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber'
      preLoaderRoute: typeof DashboardRunsTraceIdJobsJobIdStepsStepNumberRouteImport
      parentRoute: typeof DashboardRunsTraceIdRouteRoute
    }
  }
}

interface DashboardFlakyTestsRouteChildren {
  DashboardFlakyTestsDetailRoute: typeof DashboardFlakyTestsDetailRoute
  DashboardFlakyTestsIndexRoute: typeof DashboardFlakyTestsIndexRoute
}

const DashboardFlakyTestsRouteChildren: DashboardFlakyTestsRouteChildren = {
  DashboardFlakyTestsDetailRoute: DashboardFlakyTestsDetailRoute,
  DashboardFlakyTestsIndexRoute: DashboardFlakyTestsIndexRoute,
}

const DashboardFlakyTestsRouteWithChildren =
  DashboardFlakyTestsRoute._addFileChildren(DashboardFlakyTestsRouteChildren)

interface DashboardRunsTraceIdRouteRouteChildren {
  DashboardRunsTraceIdTraceRoute: typeof DashboardRunsTraceIdTraceRoute
  DashboardRunsTraceIdIndexRoute: typeof DashboardRunsTraceIdIndexRoute
  DashboardRunsTraceIdJobsJobIdIndexRoute: typeof DashboardRunsTraceIdJobsJobIdIndexRoute
  DashboardRunsTraceIdJobsJobIdStepsStepNumberRoute: typeof DashboardRunsTraceIdJobsJobIdStepsStepNumberRoute
}

const DashboardRunsTraceIdRouteRouteChildren: DashboardRunsTraceIdRouteRouteChildren =
  {
    DashboardRunsTraceIdTraceRoute: DashboardRunsTraceIdTraceRoute,
    DashboardRunsTraceIdIndexRoute: DashboardRunsTraceIdIndexRoute,
    DashboardRunsTraceIdJobsJobIdIndexRoute:
      DashboardRunsTraceIdJobsJobIdIndexRoute,
    DashboardRunsTraceIdJobsJobIdStepsStepNumberRoute:
      DashboardRunsTraceIdJobsJobIdStepsStepNumberRoute,
  }

const DashboardRunsTraceIdRouteRouteWithChildren =
  DashboardRunsTraceIdRouteRoute._addFileChildren(
    DashboardRunsTraceIdRouteRouteChildren,
  )

interface DashboardRunsRouteChildren {
  DashboardRunsTraceIdRouteRoute: typeof DashboardRunsTraceIdRouteRouteWithChildren
  DashboardRunsIndexRoute: typeof DashboardRunsIndexRoute
}

const DashboardRunsRouteChildren: DashboardRunsRouteChildren = {
  DashboardRunsTraceIdRouteRoute: DashboardRunsTraceIdRouteRouteWithChildren,
  DashboardRunsIndexRoute: DashboardRunsIndexRoute,
}

const DashboardRunsRouteWithChildren = DashboardRunsRoute._addFileChildren(
  DashboardRunsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCostAnalysisRoute: typeof DashboardCostAnalysisRoute
  DashboardFailuresRoute: typeof DashboardFailuresRoute
  DashboardFlakyTestsRoute: typeof DashboardFlakyTestsRouteWithChildren
  DashboardReposRoute: typeof DashboardReposRoute
  DashboardRunsRoute: typeof DashboardRunsRouteWithChildren
  DashboardTestResultsRoute: typeof DashboardTestResultsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardWorkflowsIndexRoute: typeof DashboardWorkflowsIndexRoute
  DashboardWorkflowsRepoWorkflowNameRoute: typeof DashboardWorkflowsRepoWorkflowNameRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCostAnalysisRoute: DashboardCostAnalysisRoute,
  DashboardFailuresRoute: DashboardFailuresRoute,
  DashboardFlakyTestsRoute: DashboardFlakyTestsRouteWithChildren,
  DashboardReposRoute: DashboardReposRoute,
  DashboardRunsRoute: DashboardRunsRouteWithChildren,
  DashboardTestResultsRoute: DashboardTestResultsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardWorkflowsIndexRoute: DashboardWorkflowsIndexRoute,
  DashboardWorkflowsRepoWorkflowNameRoute:
    DashboardWorkflowsRepoWorkflowNameRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  ApiMcpRoute: ApiMcpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
