/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as WebhookGithubRouteImport } from './routes/webhook/github'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiCliRouteImport } from './routes/api/cli'
import { Route as AuthenticatedDeviceRouteImport } from './routes/_authenticated/device'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/_dashboard'
import { Route as AuthGuestRouteImport } from './routes/_auth/_guest'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/_dashboard/index'
import { Route as ApiEventsStreamRouteImport } from './routes/api/events/stream'
import { Route as ApiCliSqlRouteImport } from './routes/api/cli/sql'
import { Route as ApiCliRunsRouteImport } from './routes/api/cli/runs'
import { Route as ApiCliReposRouteImport } from './routes/api/cli/repos'
import { Route as ApiCliOrgRouteImport } from './routes/api/cli/org'
import { Route as ApiCliNotificationRouteImport } from './routes/api/cli/notification'
import { Route as ApiCliMeRouteImport } from './routes/api/cli/me'
import { Route as ApiCliImportRouteImport } from './routes/api/cli/import'
import { Route as ApiCliGrepRouteImport } from './routes/api/cli/grep'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedDashboardUsersManagementRouteImport } from './routes/_authenticated/_dashboard/users-management'
import { Route as AuthenticatedDashboardTestsOverviewRouteImport } from './routes/_authenticated/_dashboard/tests-overview'
import { Route as AuthenticatedDashboardRunsRouteImport } from './routes/_authenticated/_dashboard/runs'
import { Route as AuthenticatedDashboardReposRouteImport } from './routes/_authenticated/_dashboard/repos'
import { Route as AuthenticatedDashboardCostAnalysisRouteImport } from './routes/_authenticated/_dashboard/cost-analysis'
import { Route as AuthenticatedDashboardBillingRouteImport } from './routes/_authenticated/_dashboard/billing'
import { Route as AuthenticatedDashboardAccountRouteImport } from './routes/_authenticated/_dashboard/account'
import { Route as AuthInviteInvitationIdRouteImport } from './routes/_auth/invite.$invitationId'
import { Route as AuthenticatedDashboardWorkflowsIndexRouteImport } from './routes/_authenticated/_dashboard/workflows/index'
import { Route as AuthenticatedDashboardRunsIndexRouteImport } from './routes/_authenticated/_dashboard/runs/index'
import { Route as ApiGithubInstallStartRouteImport } from './routes/api/github/install/start'
import { Route as ApiGithubInstallCallbackRouteImport } from './routes/api/github/install/callback'
import { Route as ApiCliRunsStatusRouteImport } from './routes/api/cli/runs/status'
import { Route as ApiCliRunsTraceIdRouteImport } from './routes/api/cli/runs/$traceId'
import { Route as ApiCliOrgNameRouteImport } from './routes/api/cli/org/name'
import { Route as AuthenticatedDashboardCheckoutSuccessRouteImport } from './routes/_authenticated/_dashboard/checkout.success'
import { Route as AuthGuestAuthSignUpRouteImport } from './routes/_auth/_guest/auth/sign-up'
import { Route as AuthGuestAuthSignInRouteImport } from './routes/_auth/_guest/auth/sign-in'
import { Route as AuthGuestAuthResetPasswordRouteImport } from './routes/_auth/_guest/auth/reset-password'
import { Route as AuthGuestAuthForgotPasswordRouteImport } from './routes/_auth/_guest/auth/forgot-password'
import { Route as AuthenticatedDashboardRunsTraceIdRouteRouteImport } from './routes/_authenticated/_dashboard/runs/$traceId/route'
import { Route as AuthenticatedDashboardRunsTraceIdIndexRouteImport } from './routes/_authenticated/_dashboard/runs/$traceId/index'
import { Route as ApiCliRunsTraceIdLogsRouteImport } from './routes/api/cli/runs/$traceId/logs'
import { Route as AuthenticatedDashboardWorkflowsRepoWorkflowNameRouteImport } from './routes/_authenticated/_dashboard/workflows/$repo/$workflowName'
import { Route as AuthenticatedDashboardRunsTraceIdTraceRouteImport } from './routes/_authenticated/_dashboard/runs/$traceId/trace'
import { Route as AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRouteImport } from './routes/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/index'
import { Route as AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRouteImport } from './routes/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhookGithubRoute = WebhookGithubRouteImport.update({
  id: '/webhook/github',
  path: '/webhook/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliRoute = ApiCliRouteImport.update({
  id: '/api/cli',
  path: '/api/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDeviceRoute = AuthenticatedDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthGuestRoute = AuthGuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiEventsStreamRoute = ApiEventsStreamRouteImport.update({
  id: '/api/events/stream',
  path: '/api/events/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliSqlRoute = ApiCliSqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => ApiCliRoute,
} as any)
const ApiCliRunsRoute = ApiCliRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => ApiCliRoute,
} as any)
const ApiCliReposRoute = ApiCliReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => ApiCliRoute,
} as any)
const ApiCliOrgRoute = ApiCliOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => ApiCliRoute,
} as any)
const ApiCliNotificationRoute = ApiCliNotificationRouteImport.update({
  id: '/notification',
  path: '/notification',
  getParentRoute: () => ApiCliRoute,
} as any)
const ApiCliMeRoute = ApiCliMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => ApiCliRoute,
} as any)
const ApiCliImportRoute = ApiCliImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ApiCliRoute,
} as any)
const ApiCliGrepRoute = ApiCliGrepRouteImport.update({
  id: '/grep',
  path: '/grep',
  getParentRoute: () => ApiCliRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardUsersManagementRoute =
  AuthenticatedDashboardUsersManagementRouteImport.update({
    id: '/users-management',
    path: '/users-management',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTestsOverviewRoute =
  AuthenticatedDashboardTestsOverviewRouteImport.update({
    id: '/tests-overview',
    path: '/tests-overview',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRunsRoute =
  AuthenticatedDashboardRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReposRoute =
  AuthenticatedDashboardReposRouteImport.update({
    id: '/repos',
    path: '/repos',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCostAnalysisRoute =
  AuthenticatedDashboardCostAnalysisRouteImport.update({
    id: '/cost-analysis',
    path: '/cost-analysis',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBillingRoute =
  AuthenticatedDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAccountRoute =
  AuthenticatedDashboardAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthInviteInvitationIdRoute = AuthInviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardWorkflowsIndexRoute =
  AuthenticatedDashboardWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRunsIndexRoute =
  AuthenticatedDashboardRunsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRunsRoute,
  } as any)
const ApiGithubInstallStartRoute = ApiGithubInstallStartRouteImport.update({
  id: '/api/github/install/start',
  path: '/api/github/install/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallCallbackRoute =
  ApiGithubInstallCallbackRouteImport.update({
    id: '/api/github/install/callback',
    path: '/api/github/install/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCliRunsStatusRoute = ApiCliRunsStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiCliRunsRoute,
} as any)
const ApiCliRunsTraceIdRoute = ApiCliRunsTraceIdRouteImport.update({
  id: '/$traceId',
  path: '/$traceId',
  getParentRoute: () => ApiCliRunsRoute,
} as any)
const ApiCliOrgNameRoute = ApiCliOrgNameRouteImport.update({
  id: '/name',
  path: '/name',
  getParentRoute: () => ApiCliOrgRoute,
} as any)
const AuthenticatedDashboardCheckoutSuccessRoute =
  AuthenticatedDashboardCheckoutSuccessRouteImport.update({
    id: '/checkout/success',
    path: '/checkout/success',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthGuestAuthSignUpRoute = AuthGuestAuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => AuthGuestRoute,
} as any)
const AuthGuestAuthSignInRoute = AuthGuestAuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => AuthGuestRoute,
} as any)
const AuthGuestAuthResetPasswordRoute =
  AuthGuestAuthResetPasswordRouteImport.update({
    id: '/auth/reset-password',
    path: '/auth/reset-password',
    getParentRoute: () => AuthGuestRoute,
  } as any)
const AuthGuestAuthForgotPasswordRoute =
  AuthGuestAuthForgotPasswordRouteImport.update({
    id: '/auth/forgot-password',
    path: '/auth/forgot-password',
    getParentRoute: () => AuthGuestRoute,
  } as any)
const AuthenticatedDashboardRunsTraceIdRouteRoute =
  AuthenticatedDashboardRunsTraceIdRouteRouteImport.update({
    id: '/$traceId',
    path: '/$traceId',
    getParentRoute: () => AuthenticatedDashboardRunsRoute,
  } as any)
const AuthenticatedDashboardRunsTraceIdIndexRoute =
  AuthenticatedDashboardRunsTraceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRunsTraceIdRouteRoute,
  } as any)
const ApiCliRunsTraceIdLogsRoute = ApiCliRunsTraceIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ApiCliRunsTraceIdRoute,
} as any)
const AuthenticatedDashboardWorkflowsRepoWorkflowNameRoute =
  AuthenticatedDashboardWorkflowsRepoWorkflowNameRouteImport.update({
    id: '/workflows/$repo/$workflowName',
    path: '/workflows/$repo/$workflowName',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRunsTraceIdTraceRoute =
  AuthenticatedDashboardRunsTraceIdTraceRouteImport.update({
    id: '/trace',
    path: '/trace',
    getParentRoute: () => AuthenticatedDashboardRunsTraceIdRouteRoute,
  } as any)
const AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRoute =
  AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRouteImport.update({
    id: '/jobs/$jobId/',
    path: '/jobs/$jobId/',
    getParentRoute: () => AuthenticatedDashboardRunsTraceIdRouteRoute,
  } as any)
const AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRoute =
  AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRouteImport.update({
    id: '/jobs/$jobId/steps/$stepNumber',
    path: '/jobs/$jobId/steps/$stepNumber',
    getParentRoute: () => AuthenticatedDashboardRunsTraceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedDashboardIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/device': typeof AuthenticatedDeviceRoute
  '/api/cli': typeof ApiCliRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/webhook/github': typeof WebhookGithubRoute
  '/invite/$invitationId': typeof AuthInviteInvitationIdRoute
  '/account': typeof AuthenticatedDashboardAccountRoute
  '/billing': typeof AuthenticatedDashboardBillingRoute
  '/cost-analysis': typeof AuthenticatedDashboardCostAnalysisRoute
  '/repos': typeof AuthenticatedDashboardReposRoute
  '/runs': typeof AuthenticatedDashboardRunsRouteWithChildren
  '/tests-overview': typeof AuthenticatedDashboardTestsOverviewRoute
  '/users-management': typeof AuthenticatedDashboardUsersManagementRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cli/grep': typeof ApiCliGrepRoute
  '/api/cli/import': typeof ApiCliImportRoute
  '/api/cli/me': typeof ApiCliMeRoute
  '/api/cli/notification': typeof ApiCliNotificationRoute
  '/api/cli/org': typeof ApiCliOrgRouteWithChildren
  '/api/cli/repos': typeof ApiCliReposRoute
  '/api/cli/runs': typeof ApiCliRunsRouteWithChildren
  '/api/cli/sql': typeof ApiCliSqlRoute
  '/api/events/stream': typeof ApiEventsStreamRoute
  '/runs/$traceId': typeof AuthenticatedDashboardRunsTraceIdRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthGuestAuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthGuestAuthResetPasswordRoute
  '/auth/sign-in': typeof AuthGuestAuthSignInRoute
  '/auth/sign-up': typeof AuthGuestAuthSignUpRoute
  '/checkout/success': typeof AuthenticatedDashboardCheckoutSuccessRoute
  '/api/cli/org/name': typeof ApiCliOrgNameRoute
  '/api/cli/runs/$traceId': typeof ApiCliRunsTraceIdRouteWithChildren
  '/api/cli/runs/status': typeof ApiCliRunsStatusRoute
  '/api/github/install/callback': typeof ApiGithubInstallCallbackRoute
  '/api/github/install/start': typeof ApiGithubInstallStartRoute
  '/runs/': typeof AuthenticatedDashboardRunsIndexRoute
  '/workflows/': typeof AuthenticatedDashboardWorkflowsIndexRoute
  '/runs/$traceId/trace': typeof AuthenticatedDashboardRunsTraceIdTraceRoute
  '/workflows/$repo/$workflowName': typeof AuthenticatedDashboardWorkflowsRepoWorkflowNameRoute
  '/api/cli/runs/$traceId/logs': typeof ApiCliRunsTraceIdLogsRoute
  '/runs/$traceId/': typeof AuthenticatedDashboardRunsTraceIdIndexRoute
  '/runs/$traceId/jobs/$jobId/': typeof AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRoute
  '/runs/$traceId/jobs/$jobId/steps/$stepNumber': typeof AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedDashboardIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/device': typeof AuthenticatedDeviceRoute
  '/api/cli': typeof ApiCliRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/webhook/github': typeof WebhookGithubRoute
  '/invite/$invitationId': typeof AuthInviteInvitationIdRoute
  '/account': typeof AuthenticatedDashboardAccountRoute
  '/billing': typeof AuthenticatedDashboardBillingRoute
  '/cost-analysis': typeof AuthenticatedDashboardCostAnalysisRoute
  '/repos': typeof AuthenticatedDashboardReposRoute
  '/tests-overview': typeof AuthenticatedDashboardTestsOverviewRoute
  '/users-management': typeof AuthenticatedDashboardUsersManagementRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cli/grep': typeof ApiCliGrepRoute
  '/api/cli/import': typeof ApiCliImportRoute
  '/api/cli/me': typeof ApiCliMeRoute
  '/api/cli/notification': typeof ApiCliNotificationRoute
  '/api/cli/org': typeof ApiCliOrgRouteWithChildren
  '/api/cli/repos': typeof ApiCliReposRoute
  '/api/cli/runs': typeof ApiCliRunsRouteWithChildren
  '/api/cli/sql': typeof ApiCliSqlRoute
  '/api/events/stream': typeof ApiEventsStreamRoute
  '/auth/forgot-password': typeof AuthGuestAuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthGuestAuthResetPasswordRoute
  '/auth/sign-in': typeof AuthGuestAuthSignInRoute
  '/auth/sign-up': typeof AuthGuestAuthSignUpRoute
  '/checkout/success': typeof AuthenticatedDashboardCheckoutSuccessRoute
  '/api/cli/org/name': typeof ApiCliOrgNameRoute
  '/api/cli/runs/$traceId': typeof ApiCliRunsTraceIdRouteWithChildren
  '/api/cli/runs/status': typeof ApiCliRunsStatusRoute
  '/api/github/install/callback': typeof ApiGithubInstallCallbackRoute
  '/api/github/install/start': typeof ApiGithubInstallStartRoute
  '/runs': typeof AuthenticatedDashboardRunsIndexRoute
  '/workflows': typeof AuthenticatedDashboardWorkflowsIndexRoute
  '/runs/$traceId/trace': typeof AuthenticatedDashboardRunsTraceIdTraceRoute
  '/workflows/$repo/$workflowName': typeof AuthenticatedDashboardWorkflowsRepoWorkflowNameRoute
  '/api/cli/runs/$traceId/logs': typeof ApiCliRunsTraceIdLogsRoute
  '/runs/$traceId': typeof AuthenticatedDashboardRunsTraceIdIndexRoute
  '/runs/$traceId/jobs/$jobId': typeof AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRoute
  '/runs/$traceId/jobs/$jobId/steps/$stepNumber': typeof AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_auth/_guest': typeof AuthGuestRouteWithChildren
  '/_authenticated/_dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/device': typeof AuthenticatedDeviceRoute
  '/api/cli': typeof ApiCliRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/webhook/github': typeof WebhookGithubRoute
  '/_auth/invite/$invitationId': typeof AuthInviteInvitationIdRoute
  '/_authenticated/_dashboard/account': typeof AuthenticatedDashboardAccountRoute
  '/_authenticated/_dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/_authenticated/_dashboard/cost-analysis': typeof AuthenticatedDashboardCostAnalysisRoute
  '/_authenticated/_dashboard/repos': typeof AuthenticatedDashboardReposRoute
  '/_authenticated/_dashboard/runs': typeof AuthenticatedDashboardRunsRouteWithChildren
  '/_authenticated/_dashboard/tests-overview': typeof AuthenticatedDashboardTestsOverviewRoute
  '/_authenticated/_dashboard/users-management': typeof AuthenticatedDashboardUsersManagementRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cli/grep': typeof ApiCliGrepRoute
  '/api/cli/import': typeof ApiCliImportRoute
  '/api/cli/me': typeof ApiCliMeRoute
  '/api/cli/notification': typeof ApiCliNotificationRoute
  '/api/cli/org': typeof ApiCliOrgRouteWithChildren
  '/api/cli/repos': typeof ApiCliReposRoute
  '/api/cli/runs': typeof ApiCliRunsRouteWithChildren
  '/api/cli/sql': typeof ApiCliSqlRoute
  '/api/events/stream': typeof ApiEventsStreamRoute
  '/_authenticated/_dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/_dashboard/runs/$traceId': typeof AuthenticatedDashboardRunsTraceIdRouteRouteWithChildren
  '/_auth/_guest/auth/forgot-password': typeof AuthGuestAuthForgotPasswordRoute
  '/_auth/_guest/auth/reset-password': typeof AuthGuestAuthResetPasswordRoute
  '/_auth/_guest/auth/sign-in': typeof AuthGuestAuthSignInRoute
  '/_auth/_guest/auth/sign-up': typeof AuthGuestAuthSignUpRoute
  '/_authenticated/_dashboard/checkout/success': typeof AuthenticatedDashboardCheckoutSuccessRoute
  '/api/cli/org/name': typeof ApiCliOrgNameRoute
  '/api/cli/runs/$traceId': typeof ApiCliRunsTraceIdRouteWithChildren
  '/api/cli/runs/status': typeof ApiCliRunsStatusRoute
  '/api/github/install/callback': typeof ApiGithubInstallCallbackRoute
  '/api/github/install/start': typeof ApiGithubInstallStartRoute
  '/_authenticated/_dashboard/runs/': typeof AuthenticatedDashboardRunsIndexRoute
  '/_authenticated/_dashboard/workflows/': typeof AuthenticatedDashboardWorkflowsIndexRoute
  '/_authenticated/_dashboard/runs/$traceId/trace': typeof AuthenticatedDashboardRunsTraceIdTraceRoute
  '/_authenticated/_dashboard/workflows/$repo/$workflowName': typeof AuthenticatedDashboardWorkflowsRepoWorkflowNameRoute
  '/api/cli/runs/$traceId/logs': typeof ApiCliRunsTraceIdLogsRoute
  '/_authenticated/_dashboard/runs/$traceId/': typeof AuthenticatedDashboardRunsTraceIdIndexRoute
  '/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/': typeof AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRoute
  '/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber': typeof AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/device'
    | '/api/cli'
    | '/api/health'
    | '/webhook/github'
    | '/invite/$invitationId'
    | '/account'
    | '/billing'
    | '/cost-analysis'
    | '/repos'
    | '/runs'
    | '/tests-overview'
    | '/users-management'
    | '/api/auth/$'
    | '/api/cli/grep'
    | '/api/cli/import'
    | '/api/cli/me'
    | '/api/cli/notification'
    | '/api/cli/org'
    | '/api/cli/repos'
    | '/api/cli/runs'
    | '/api/cli/sql'
    | '/api/events/stream'
    | '/runs/$traceId'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/checkout/success'
    | '/api/cli/org/name'
    | '/api/cli/runs/$traceId'
    | '/api/cli/runs/status'
    | '/api/github/install/callback'
    | '/api/github/install/start'
    | '/runs/'
    | '/workflows/'
    | '/runs/$traceId/trace'
    | '/workflows/$repo/$workflowName'
    | '/api/cli/runs/$traceId/logs'
    | '/runs/$traceId/'
    | '/runs/$traceId/jobs/$jobId/'
    | '/runs/$traceId/jobs/$jobId/steps/$stepNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/device'
    | '/api/cli'
    | '/api/health'
    | '/webhook/github'
    | '/invite/$invitationId'
    | '/account'
    | '/billing'
    | '/cost-analysis'
    | '/repos'
    | '/tests-overview'
    | '/users-management'
    | '/api/auth/$'
    | '/api/cli/grep'
    | '/api/cli/import'
    | '/api/cli/me'
    | '/api/cli/notification'
    | '/api/cli/org'
    | '/api/cli/repos'
    | '/api/cli/runs'
    | '/api/cli/sql'
    | '/api/events/stream'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/checkout/success'
    | '/api/cli/org/name'
    | '/api/cli/runs/$traceId'
    | '/api/cli/runs/status'
    | '/api/github/install/callback'
    | '/api/github/install/start'
    | '/runs'
    | '/workflows'
    | '/runs/$traceId/trace'
    | '/workflows/$repo/$workflowName'
    | '/api/cli/runs/$traceId/logs'
    | '/runs/$traceId'
    | '/runs/$traceId/jobs/$jobId'
    | '/runs/$traceId/jobs/$jobId/steps/$stepNumber'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/onboarding'
    | '/_auth/_guest'
    | '/_authenticated/_dashboard'
    | '/_authenticated/device'
    | '/api/cli'
    | '/api/health'
    | '/webhook/github'
    | '/_auth/invite/$invitationId'
    | '/_authenticated/_dashboard/account'
    | '/_authenticated/_dashboard/billing'
    | '/_authenticated/_dashboard/cost-analysis'
    | '/_authenticated/_dashboard/repos'
    | '/_authenticated/_dashboard/runs'
    | '/_authenticated/_dashboard/tests-overview'
    | '/_authenticated/_dashboard/users-management'
    | '/api/auth/$'
    | '/api/cli/grep'
    | '/api/cli/import'
    | '/api/cli/me'
    | '/api/cli/notification'
    | '/api/cli/org'
    | '/api/cli/repos'
    | '/api/cli/runs'
    | '/api/cli/sql'
    | '/api/events/stream'
    | '/_authenticated/_dashboard/'
    | '/_authenticated/_dashboard/runs/$traceId'
    | '/_auth/_guest/auth/forgot-password'
    | '/_auth/_guest/auth/reset-password'
    | '/_auth/_guest/auth/sign-in'
    | '/_auth/_guest/auth/sign-up'
    | '/_authenticated/_dashboard/checkout/success'
    | '/api/cli/org/name'
    | '/api/cli/runs/$traceId'
    | '/api/cli/runs/status'
    | '/api/github/install/callback'
    | '/api/github/install/start'
    | '/_authenticated/_dashboard/runs/'
    | '/_authenticated/_dashboard/workflows/'
    | '/_authenticated/_dashboard/runs/$traceId/trace'
    | '/_authenticated/_dashboard/workflows/$repo/$workflowName'
    | '/api/cli/runs/$traceId/logs'
    | '/_authenticated/_dashboard/runs/$traceId/'
    | '/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/'
    | '/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ApiCliRoute: typeof ApiCliRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  WebhookGithubRoute: typeof WebhookGithubRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiEventsStreamRoute: typeof ApiEventsStreamRoute
  ApiGithubInstallCallbackRoute: typeof ApiGithubInstallCallbackRoute
  ApiGithubInstallStartRoute: typeof ApiGithubInstallStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhook/github': {
      id: '/webhook/github'
      path: '/webhook/github'
      fullPath: '/webhook/github'
      preLoaderRoute: typeof WebhookGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli': {
      id: '/api/cli'
      path: '/api/cli'
      fullPath: '/api/cli'
      preLoaderRoute: typeof ApiCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/device': {
      id: '/_authenticated/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof AuthenticatedDeviceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dashboard': {
      id: '/_authenticated/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/_guest': {
      id: '/_auth/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthGuestRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/_dashboard/': {
      id: '/_authenticated/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/events/stream': {
      id: '/api/events/stream'
      path: '/api/events/stream'
      fullPath: '/api/events/stream'
      preLoaderRoute: typeof ApiEventsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/sql': {
      id: '/api/cli/sql'
      path: '/sql'
      fullPath: '/api/cli/sql'
      preLoaderRoute: typeof ApiCliSqlRouteImport
      parentRoute: typeof ApiCliRoute
    }
    '/api/cli/runs': {
      id: '/api/cli/runs'
      path: '/runs'
      fullPath: '/api/cli/runs'
      preLoaderRoute: typeof ApiCliRunsRouteImport
      parentRoute: typeof ApiCliRoute
    }
    '/api/cli/repos': {
      id: '/api/cli/repos'
      path: '/repos'
      fullPath: '/api/cli/repos'
      preLoaderRoute: typeof ApiCliReposRouteImport
      parentRoute: typeof ApiCliRoute
    }
    '/api/cli/org': {
      id: '/api/cli/org'
      path: '/org'
      fullPath: '/api/cli/org'
      preLoaderRoute: typeof ApiCliOrgRouteImport
      parentRoute: typeof ApiCliRoute
    }
    '/api/cli/notification': {
      id: '/api/cli/notification'
      path: '/notification'
      fullPath: '/api/cli/notification'
      preLoaderRoute: typeof ApiCliNotificationRouteImport
      parentRoute: typeof ApiCliRoute
    }
    '/api/cli/me': {
      id: '/api/cli/me'
      path: '/me'
      fullPath: '/api/cli/me'
      preLoaderRoute: typeof ApiCliMeRouteImport
      parentRoute: typeof ApiCliRoute
    }
    '/api/cli/import': {
      id: '/api/cli/import'
      path: '/import'
      fullPath: '/api/cli/import'
      preLoaderRoute: typeof ApiCliImportRouteImport
      parentRoute: typeof ApiCliRoute
    }
    '/api/cli/grep': {
      id: '/api/cli/grep'
      path: '/grep'
      fullPath: '/api/cli/grep'
      preLoaderRoute: typeof ApiCliGrepRouteImport
      parentRoute: typeof ApiCliRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_dashboard/users-management': {
      id: '/_authenticated/_dashboard/users-management'
      path: '/users-management'
      fullPath: '/users-management'
      preLoaderRoute: typeof AuthenticatedDashboardUsersManagementRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/tests-overview': {
      id: '/_authenticated/_dashboard/tests-overview'
      path: '/tests-overview'
      fullPath: '/tests-overview'
      preLoaderRoute: typeof AuthenticatedDashboardTestsOverviewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/runs': {
      id: '/_authenticated/_dashboard/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof AuthenticatedDashboardRunsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/repos': {
      id: '/_authenticated/_dashboard/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof AuthenticatedDashboardReposRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/cost-analysis': {
      id: '/_authenticated/_dashboard/cost-analysis'
      path: '/cost-analysis'
      fullPath: '/cost-analysis'
      preLoaderRoute: typeof AuthenticatedDashboardCostAnalysisRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/billing': {
      id: '/_authenticated/_dashboard/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedDashboardBillingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/account': {
      id: '/_authenticated/_dashboard/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedDashboardAccountRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_auth/invite/$invitationId': {
      id: '/_auth/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof AuthInviteInvitationIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/_dashboard/workflows/': {
      id: '/_authenticated/_dashboard/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AuthenticatedDashboardWorkflowsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/runs/': {
      id: '/_authenticated/_dashboard/runs/'
      path: '/'
      fullPath: '/runs/'
      preLoaderRoute: typeof AuthenticatedDashboardRunsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRunsRoute
    }
    '/api/github/install/start': {
      id: '/api/github/install/start'
      path: '/api/github/install/start'
      fullPath: '/api/github/install/start'
      preLoaderRoute: typeof ApiGithubInstallStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/install/callback': {
      id: '/api/github/install/callback'
      path: '/api/github/install/callback'
      fullPath: '/api/github/install/callback'
      preLoaderRoute: typeof ApiGithubInstallCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/runs/status': {
      id: '/api/cli/runs/status'
      path: '/status'
      fullPath: '/api/cli/runs/status'
      preLoaderRoute: typeof ApiCliRunsStatusRouteImport
      parentRoute: typeof ApiCliRunsRoute
    }
    '/api/cli/runs/$traceId': {
      id: '/api/cli/runs/$traceId'
      path: '/$traceId'
      fullPath: '/api/cli/runs/$traceId'
      preLoaderRoute: typeof ApiCliRunsTraceIdRouteImport
      parentRoute: typeof ApiCliRunsRoute
    }
    '/api/cli/org/name': {
      id: '/api/cli/org/name'
      path: '/name'
      fullPath: '/api/cli/org/name'
      preLoaderRoute: typeof ApiCliOrgNameRouteImport
      parentRoute: typeof ApiCliOrgRoute
    }
    '/_authenticated/_dashboard/checkout/success': {
      id: '/_authenticated/_dashboard/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof AuthenticatedDashboardCheckoutSuccessRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_auth/_guest/auth/sign-up': {
      id: '/_auth/_guest/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthGuestAuthSignUpRouteImport
      parentRoute: typeof AuthGuestRoute
    }
    '/_auth/_guest/auth/sign-in': {
      id: '/_auth/_guest/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthGuestAuthSignInRouteImport
      parentRoute: typeof AuthGuestRoute
    }
    '/_auth/_guest/auth/reset-password': {
      id: '/_auth/_guest/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthGuestAuthResetPasswordRouteImport
      parentRoute: typeof AuthGuestRoute
    }
    '/_auth/_guest/auth/forgot-password': {
      id: '/_auth/_guest/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthGuestAuthForgotPasswordRouteImport
      parentRoute: typeof AuthGuestRoute
    }
    '/_authenticated/_dashboard/runs/$traceId': {
      id: '/_authenticated/_dashboard/runs/$traceId'
      path: '/$traceId'
      fullPath: '/runs/$traceId'
      preLoaderRoute: typeof AuthenticatedDashboardRunsTraceIdRouteRouteImport
      parentRoute: typeof AuthenticatedDashboardRunsRoute
    }
    '/_authenticated/_dashboard/runs/$traceId/': {
      id: '/_authenticated/_dashboard/runs/$traceId/'
      path: '/'
      fullPath: '/runs/$traceId/'
      preLoaderRoute: typeof AuthenticatedDashboardRunsTraceIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRunsTraceIdRouteRoute
    }
    '/api/cli/runs/$traceId/logs': {
      id: '/api/cli/runs/$traceId/logs'
      path: '/logs'
      fullPath: '/api/cli/runs/$traceId/logs'
      preLoaderRoute: typeof ApiCliRunsTraceIdLogsRouteImport
      parentRoute: typeof ApiCliRunsTraceIdRoute
    }
    '/_authenticated/_dashboard/workflows/$repo/$workflowName': {
      id: '/_authenticated/_dashboard/workflows/$repo/$workflowName'
      path: '/workflows/$repo/$workflowName'
      fullPath: '/workflows/$repo/$workflowName'
      preLoaderRoute: typeof AuthenticatedDashboardWorkflowsRepoWorkflowNameRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/_dashboard/runs/$traceId/trace': {
      id: '/_authenticated/_dashboard/runs/$traceId/trace'
      path: '/trace'
      fullPath: '/runs/$traceId/trace'
      preLoaderRoute: typeof AuthenticatedDashboardRunsTraceIdTraceRouteImport
      parentRoute: typeof AuthenticatedDashboardRunsTraceIdRouteRoute
    }
    '/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/': {
      id: '/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/'
      path: '/jobs/$jobId'
      fullPath: '/runs/$traceId/jobs/$jobId/'
      preLoaderRoute: typeof AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRunsTraceIdRouteRoute
    }
    '/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber': {
      id: '/_authenticated/_dashboard/runs/$traceId/jobs/$jobId/steps/$stepNumber'
      path: '/jobs/$jobId/steps/$stepNumber'
      fullPath: '/runs/$traceId/jobs/$jobId/steps/$stepNumber'
      preLoaderRoute: typeof AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRouteImport
      parentRoute: typeof AuthenticatedDashboardRunsTraceIdRouteRoute
    }
  }
}

interface AuthGuestRouteChildren {
  AuthGuestAuthForgotPasswordRoute: typeof AuthGuestAuthForgotPasswordRoute
  AuthGuestAuthResetPasswordRoute: typeof AuthGuestAuthResetPasswordRoute
  AuthGuestAuthSignInRoute: typeof AuthGuestAuthSignInRoute
  AuthGuestAuthSignUpRoute: typeof AuthGuestAuthSignUpRoute
}

const AuthGuestRouteChildren: AuthGuestRouteChildren = {
  AuthGuestAuthForgotPasswordRoute: AuthGuestAuthForgotPasswordRoute,
  AuthGuestAuthResetPasswordRoute: AuthGuestAuthResetPasswordRoute,
  AuthGuestAuthSignInRoute: AuthGuestAuthSignInRoute,
  AuthGuestAuthSignUpRoute: AuthGuestAuthSignUpRoute,
}

const AuthGuestRouteWithChildren = AuthGuestRoute._addFileChildren(
  AuthGuestRouteChildren,
)

interface AuthRouteChildren {
  AuthGuestRoute: typeof AuthGuestRouteWithChildren
  AuthInviteInvitationIdRoute: typeof AuthInviteInvitationIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthGuestRoute: AuthGuestRouteWithChildren,
  AuthInviteInvitationIdRoute: AuthInviteInvitationIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedDashboardRunsTraceIdRouteRouteChildren {
  AuthenticatedDashboardRunsTraceIdTraceRoute: typeof AuthenticatedDashboardRunsTraceIdTraceRoute
  AuthenticatedDashboardRunsTraceIdIndexRoute: typeof AuthenticatedDashboardRunsTraceIdIndexRoute
  AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRoute: typeof AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRoute
  AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRoute: typeof AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRoute
}

const AuthenticatedDashboardRunsTraceIdRouteRouteChildren: AuthenticatedDashboardRunsTraceIdRouteRouteChildren =
  {
    AuthenticatedDashboardRunsTraceIdTraceRoute:
      AuthenticatedDashboardRunsTraceIdTraceRoute,
    AuthenticatedDashboardRunsTraceIdIndexRoute:
      AuthenticatedDashboardRunsTraceIdIndexRoute,
    AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRoute:
      AuthenticatedDashboardRunsTraceIdJobsJobIdIndexRoute,
    AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRoute:
      AuthenticatedDashboardRunsTraceIdJobsJobIdStepsStepNumberRoute,
  }

const AuthenticatedDashboardRunsTraceIdRouteRouteWithChildren =
  AuthenticatedDashboardRunsTraceIdRouteRoute._addFileChildren(
    AuthenticatedDashboardRunsTraceIdRouteRouteChildren,
  )

interface AuthenticatedDashboardRunsRouteChildren {
  AuthenticatedDashboardRunsTraceIdRouteRoute: typeof AuthenticatedDashboardRunsTraceIdRouteRouteWithChildren
  AuthenticatedDashboardRunsIndexRoute: typeof AuthenticatedDashboardRunsIndexRoute
}

const AuthenticatedDashboardRunsRouteChildren: AuthenticatedDashboardRunsRouteChildren =
  {
    AuthenticatedDashboardRunsTraceIdRouteRoute:
      AuthenticatedDashboardRunsTraceIdRouteRouteWithChildren,
    AuthenticatedDashboardRunsIndexRoute: AuthenticatedDashboardRunsIndexRoute,
  }

const AuthenticatedDashboardRunsRouteWithChildren =
  AuthenticatedDashboardRunsRoute._addFileChildren(
    AuthenticatedDashboardRunsRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAccountRoute: typeof AuthenticatedDashboardAccountRoute
  AuthenticatedDashboardBillingRoute: typeof AuthenticatedDashboardBillingRoute
  AuthenticatedDashboardCostAnalysisRoute: typeof AuthenticatedDashboardCostAnalysisRoute
  AuthenticatedDashboardReposRoute: typeof AuthenticatedDashboardReposRoute
  AuthenticatedDashboardRunsRoute: typeof AuthenticatedDashboardRunsRouteWithChildren
  AuthenticatedDashboardTestsOverviewRoute: typeof AuthenticatedDashboardTestsOverviewRoute
  AuthenticatedDashboardUsersManagementRoute: typeof AuthenticatedDashboardUsersManagementRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardCheckoutSuccessRoute: typeof AuthenticatedDashboardCheckoutSuccessRoute
  AuthenticatedDashboardWorkflowsIndexRoute: typeof AuthenticatedDashboardWorkflowsIndexRoute
  AuthenticatedDashboardWorkflowsRepoWorkflowNameRoute: typeof AuthenticatedDashboardWorkflowsRepoWorkflowNameRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAccountRoute: AuthenticatedDashboardAccountRoute,
    AuthenticatedDashboardBillingRoute: AuthenticatedDashboardBillingRoute,
    AuthenticatedDashboardCostAnalysisRoute:
      AuthenticatedDashboardCostAnalysisRoute,
    AuthenticatedDashboardReposRoute: AuthenticatedDashboardReposRoute,
    AuthenticatedDashboardRunsRoute:
      AuthenticatedDashboardRunsRouteWithChildren,
    AuthenticatedDashboardTestsOverviewRoute:
      AuthenticatedDashboardTestsOverviewRoute,
    AuthenticatedDashboardUsersManagementRoute:
      AuthenticatedDashboardUsersManagementRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardCheckoutSuccessRoute:
      AuthenticatedDashboardCheckoutSuccessRoute,
    AuthenticatedDashboardWorkflowsIndexRoute:
      AuthenticatedDashboardWorkflowsIndexRoute,
    AuthenticatedDashboardWorkflowsRepoWorkflowNameRoute:
      AuthenticatedDashboardWorkflowsRepoWorkflowNameRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedDeviceRoute: typeof AuthenticatedDeviceRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedDeviceRoute: AuthenticatedDeviceRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiCliOrgRouteChildren {
  ApiCliOrgNameRoute: typeof ApiCliOrgNameRoute
}

const ApiCliOrgRouteChildren: ApiCliOrgRouteChildren = {
  ApiCliOrgNameRoute: ApiCliOrgNameRoute,
}

const ApiCliOrgRouteWithChildren = ApiCliOrgRoute._addFileChildren(
  ApiCliOrgRouteChildren,
)

interface ApiCliRunsTraceIdRouteChildren {
  ApiCliRunsTraceIdLogsRoute: typeof ApiCliRunsTraceIdLogsRoute
}

const ApiCliRunsTraceIdRouteChildren: ApiCliRunsTraceIdRouteChildren = {
  ApiCliRunsTraceIdLogsRoute: ApiCliRunsTraceIdLogsRoute,
}

const ApiCliRunsTraceIdRouteWithChildren =
  ApiCliRunsTraceIdRoute._addFileChildren(ApiCliRunsTraceIdRouteChildren)

interface ApiCliRunsRouteChildren {
  ApiCliRunsTraceIdRoute: typeof ApiCliRunsTraceIdRouteWithChildren
  ApiCliRunsStatusRoute: typeof ApiCliRunsStatusRoute
}

const ApiCliRunsRouteChildren: ApiCliRunsRouteChildren = {
  ApiCliRunsTraceIdRoute: ApiCliRunsTraceIdRouteWithChildren,
  ApiCliRunsStatusRoute: ApiCliRunsStatusRoute,
}

const ApiCliRunsRouteWithChildren = ApiCliRunsRoute._addFileChildren(
  ApiCliRunsRouteChildren,
)

interface ApiCliRouteChildren {
  ApiCliGrepRoute: typeof ApiCliGrepRoute
  ApiCliImportRoute: typeof ApiCliImportRoute
  ApiCliMeRoute: typeof ApiCliMeRoute
  ApiCliNotificationRoute: typeof ApiCliNotificationRoute
  ApiCliOrgRoute: typeof ApiCliOrgRouteWithChildren
  ApiCliReposRoute: typeof ApiCliReposRoute
  ApiCliRunsRoute: typeof ApiCliRunsRouteWithChildren
  ApiCliSqlRoute: typeof ApiCliSqlRoute
}

const ApiCliRouteChildren: ApiCliRouteChildren = {
  ApiCliGrepRoute: ApiCliGrepRoute,
  ApiCliImportRoute: ApiCliImportRoute,
  ApiCliMeRoute: ApiCliMeRoute,
  ApiCliNotificationRoute: ApiCliNotificationRoute,
  ApiCliOrgRoute: ApiCliOrgRouteWithChildren,
  ApiCliReposRoute: ApiCliReposRoute,
  ApiCliRunsRoute: ApiCliRunsRouteWithChildren,
  ApiCliSqlRoute: ApiCliSqlRoute,
}

const ApiCliRouteWithChildren =
  ApiCliRoute._addFileChildren(ApiCliRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ApiCliRoute: ApiCliRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  WebhookGithubRoute: WebhookGithubRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiEventsStreamRoute: ApiEventsStreamRoute,
  ApiGithubInstallCallbackRoute: ApiGithubInstallCallbackRoute,
  ApiGithubInstallStartRoute: ApiGithubInstallStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
