/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthenticatedAppImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppIndexImport } from './routes/_authenticated/_app/index'
import { Route as AuthenticatedAppSettingsIndexImport } from './routes/_authenticated/_app/settings/index'
import { Route as AuthenticatedAppReposOrgRepoImport } from './routes/_authenticated/_app/repos/$org.$repo'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AuthenticatedAppRoute = AuthenticatedAppImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAppIndexRoute = AuthenticatedAppIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

const AuthenticatedAppSettingsIndexRoute =
  AuthenticatedAppSettingsIndexImport.update({
    path: '/settings/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

const AuthenticatedAppReposOrgRepoRoute =
  AuthenticatedAppReposOrgRepoImport.update({
    path: '/repos/$org/$repo',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedAppImport
      parentRoute: typeof AuthenticatedImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_authenticated/_app/': {
      id: '/_authenticated/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/settings/': {
      id: '/_authenticated/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/repos/$org/$repo': {
      id: '/_authenticated/_app/repos/$org/$repo'
      path: '/repos/$org/$repo'
      fullPath: '/repos/$org/$repo'
      preLoaderRoute: typeof AuthenticatedAppReposOrgRepoImport
      parentRoute: typeof AuthenticatedAppImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppSettingsIndexRoute: typeof AuthenticatedAppSettingsIndexRoute
  AuthenticatedAppReposOrgRepoRoute: typeof AuthenticatedAppReposOrgRepoRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppSettingsIndexRoute: AuthenticatedAppSettingsIndexRoute,
  AuthenticatedAppReposOrgRepoRoute: AuthenticatedAppReposOrgRepoRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedAppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AuthenticatedAppIndexRoute
  '/settings': typeof AuthenticatedAppSettingsIndexRoute
  '/repos/$org/$repo': typeof AuthenticatedAppReposOrgRepoRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AuthenticatedAppIndexRoute
  '/settings': typeof AuthenticatedAppSettingsIndexRoute
  '/repos/$org/$repo': typeof AuthenticatedAppReposOrgRepoRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_authenticated/_app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/_app/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/_authenticated/_app/repos/$org/$repo': typeof AuthenticatedAppReposOrgRepoRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/auth'
    | '/auth/login'
    | '/'
    | '/settings'
    | '/repos/$org/$repo'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/auth' | '/auth/login' | '/' | '/settings' | '/repos/$org/$repo'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_app'
    | '/auth/login'
    | '/_authenticated/_app/'
    | '/_authenticated/_app/settings/'
    | '/_authenticated/_app/repos/$org/$repo'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/auth"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_app"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/login"
      ]
    },
    "/_authenticated/_app": {
      "filePath": "_authenticated/_app.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_app/",
        "/_authenticated/_app/settings/",
        "/_authenticated/_app/repos/$org/$repo"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login.tsx",
      "parent": "/auth"
    },
    "/_authenticated/_app/": {
      "filePath": "_authenticated/_app/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/settings/": {
      "filePath": "_authenticated/_app/settings/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/repos/$org/$repo": {
      "filePath": "_authenticated/_app/repos/$org.$repo.tsx",
      "parent": "/_authenticated/_app"
    }
  }
}
ROUTE_MANIFEST_END */
