/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthRecoverPasswordImport } from './routes/auth/recover-password'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthenticatedAppImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppIndexImport } from './routes/_authenticated/_app/index'
import { Route as AuthenticatedAppReposOrgRepoIndexImport } from './routes/_authenticated/_app/repos/$org.$repo/index'
import { Route as AuthenticatedAppReposOrgRepoRunTraceIdSplatImport } from './routes/_authenticated/_app/repos/$org.$repo/run/$traceId.$'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)

const AuthRecoverPasswordRoute = AuthRecoverPasswordImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AuthenticatedAppRoute = AuthenticatedAppImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAppIndexRoute = AuthenticatedAppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

const AuthenticatedAppReposOrgRepoIndexRoute =
  AuthenticatedAppReposOrgRepoIndexImport.update({
    id: '/repos/$org/$repo/',
    path: '/repos/$org/$repo/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

const AuthenticatedAppReposOrgRepoRunTraceIdSplatRoute =
  AuthenticatedAppReposOrgRepoRunTraceIdSplatImport.update({
    id: '/repos/$org/$repo/run/$traceId/$',
    path: '/repos/$org/$repo/run/$traceId/$',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedAppImport
      parentRoute: typeof AuthenticatedImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/auth/recover-password': {
      id: '/auth/recover-password'
      path: '/recover-password'
      fullPath: '/auth/recover-password'
      preLoaderRoute: typeof AuthRecoverPasswordImport
      parentRoute: typeof AuthImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthImport
    }
    '/_authenticated/_app/': {
      id: '/_authenticated/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/repos/$org/$repo/': {
      id: '/_authenticated/_app/repos/$org/$repo/'
      path: '/repos/$org/$repo'
      fullPath: '/repos/$org/$repo'
      preLoaderRoute: typeof AuthenticatedAppReposOrgRepoIndexImport
      parentRoute: typeof AuthenticatedAppImport
    }
    '/_authenticated/_app/repos/$org/$repo/run/$traceId/$': {
      id: '/_authenticated/_app/repos/$org/$repo/run/$traceId/$'
      path: '/repos/$org/$repo/run/$traceId/$'
      fullPath: '/repos/$org/$repo/run/$traceId/$'
      preLoaderRoute: typeof AuthenticatedAppReposOrgRepoRunTraceIdSplatImport
      parentRoute: typeof AuthenticatedAppImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppReposOrgRepoIndexRoute: typeof AuthenticatedAppReposOrgRepoIndexRoute
  AuthenticatedAppReposOrgRepoRunTraceIdSplatRoute: typeof AuthenticatedAppReposOrgRepoRunTraceIdSplatRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppReposOrgRepoIndexRoute:
    AuthenticatedAppReposOrgRepoIndexRoute,
  AuthenticatedAppReposOrgRepoRunTraceIdSplatRoute:
    AuthenticatedAppReposOrgRepoRunTraceIdSplatRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecoverPasswordRoute: typeof AuthRecoverPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRecoverPasswordRoute: AuthRecoverPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedAppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover-password': typeof AuthRecoverPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof AuthenticatedAppIndexRoute
  '/repos/$org/$repo': typeof AuthenticatedAppReposOrgRepoIndexRoute
  '/repos/$org/$repo/run/$traceId/$': typeof AuthenticatedAppReposOrgRepoRunTraceIdSplatRoute
}

export interface FileRoutesByTo {
  '': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover-password': typeof AuthRecoverPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof AuthenticatedAppIndexRoute
  '/repos/$org/$repo': typeof AuthenticatedAppReposOrgRepoIndexRoute
  '/repos/$org/$repo/run/$traceId/$': typeof AuthenticatedAppReposOrgRepoRunTraceIdSplatRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/recover-password': typeof AuthRecoverPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_authenticated/_app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/_app/repos/$org/$repo/': typeof AuthenticatedAppReposOrgRepoIndexRoute
  '/_authenticated/_app/repos/$org/$repo/run/$traceId/$': typeof AuthenticatedAppReposOrgRepoRunTraceIdSplatRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/auth'
    | '/auth/login'
    | '/auth/recover-password'
    | '/auth/signup'
    | '/'
    | '/repos/$org/$repo'
    | '/repos/$org/$repo/run/$traceId/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/auth'
    | '/auth/login'
    | '/auth/recover-password'
    | '/auth/signup'
    | '/'
    | '/repos/$org/$repo'
    | '/repos/$org/$repo/run/$traceId/$'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_app'
    | '/auth/login'
    | '/auth/recover-password'
    | '/auth/signup'
    | '/_authenticated/_app/'
    | '/_authenticated/_app/repos/$org/$repo/'
    | '/_authenticated/_app/repos/$org/$repo/run/$traceId/$'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/auth"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_app"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/login",
        "/auth/recover-password",
        "/auth/signup"
      ]
    },
    "/_authenticated/_app": {
      "filePath": "_authenticated/_app.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_app/",
        "/_authenticated/_app/repos/$org/$repo/",
        "/_authenticated/_app/repos/$org/$repo/run/$traceId/$"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login.tsx",
      "parent": "/auth"
    },
    "/auth/recover-password": {
      "filePath": "auth/recover-password.tsx",
      "parent": "/auth"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx",
      "parent": "/auth"
    },
    "/_authenticated/_app/": {
      "filePath": "_authenticated/_app/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/repos/$org/$repo/": {
      "filePath": "_authenticated/_app/repos/$org.$repo/index.tsx",
      "parent": "/_authenticated/_app"
    },
    "/_authenticated/_app/repos/$org/$repo/run/$traceId/$": {
      "filePath": "_authenticated/_app/repos/$org.$repo/run/$traceId.$.tsx",
      "parent": "/_authenticated/_app"
    }
  }
}
ROUTE_MANIFEST_END */
