services:
  clickhouse:
    build: ./clickhouse
    ports:
      - "8123:8123"
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query 'SELECT 1'"]
      interval: 5s
      timeout: 3s
      retries: 20
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: citric
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      COLLECTOR_RW_PASSWORD: collector-dev
      APP_RO_PASSWORD: app-dev
      APP_CDEVENTS_RW_PASSWORD: app-cdevents-dev
    volumes:
      - ./volumes/clickhouse:/var/lib/clickhouse

  postgres:
    image: postgres:18.3-alpine3.23
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql

  collector:
    build: ./collector
    depends_on:
      clickhouse:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./collector/config.yml:/etc/citric-collector/config.yaml:ro
      - ./collector/dev-everr-app.pem:/etc/citric-collector/dev-everr-app.pem:ro
