import { defineConfig } from "vite-plus";

const ignorePatterns = [
  "**/routeTree.gen.ts",
  "**/.source/**",
  "**/dist/**",
  "**/.output/**",
  "**/.nitro/**",
  "**/.tanstack/**",
  "**/tests/fixtures/**",
  // TOML stays out: oxfmt collapses Cargo.toml arrays and there is no separate
  // Rust/TOML formatter wired up here.
  "**/*.toml",
  // Collector component READMEs are generated by mdatagen (a status section
  // between autogenerated markers), so `make generate` rewrites them and
  // formatting here would fail CI's codegen diff. Only these are excluded;
  // handwritten collector markdown/yaml is formatted like everything else.
  "collector/*/*/README.md",
  // Generated / tool-managed files: Drizzle snapshots must match drizzle-kit's
  // output byte-for-byte (CI regenerates and diffs them), and these others are
  // written by their own tooling. (JS/TS/JSON/CSS/YAML/Markdown are formatted.)
  "**/drizzle/**",
  "**/.cta.json",
  "**/tauri.conf.json",
  "**/.vscode/**",
  "packages/docs/content/**/*.json",
  "packages/docs/cli.json",
];

export default defineConfig({
  fmt: { ignorePatterns },
  lint: {
    ignorePatterns,
    jsPlugins: [
      { name: "vite-plus", specifier: "vite-plus/oxlint-plugin" },
      // Aliased to a short name: oxlint's jsPlugins alias form is the supported
      // way to load scoped (`@tanstack/...`) ESLint plugins, so rules are
      // referenced as `query/*` below.
      { name: "query", specifier: "@tanstack/eslint-plugin-query" },
      // NOTE: @tanstack/eslint-plugin-router is intentionally omitted. Its
      // `create-route-property-order` rule crashes under oxlint's (alpha)
      // JS-plugin runtime on valid conditional-spread syntax
      // (`Unsupported spread element`). Revisit when oxlint gains native
      // TanStack Router support or the plugin's oxlint compat is fixed.
    ],
    rules: {
      "vite-plus/prefer-vite-plus-imports": "error",
      // @tanstack/eslint-plugin-query, all at error. `exhaustive-deps` mostly
      // flags our query-options-factory convention (spreading an input object's
      // primitive fields into the key, dependency-injected repos, `refresh`
      // deliberately excluded from the key); those are false positives suppressed
      // inline at each site, so the rule still catches genuinely missing queryKey
      // deps in new code.
      "query/exhaustive-deps": "error",
      "query/no-rest-destructuring": "error",
      "query/stable-query-client": "error",
      "query/no-unstable-deps": "error",
      "query/infinite-query-property-order": "error",
      "query/no-void-query-fn": "error",
      "query/mutation-property-order": "error",
      // No type assertions and no non-null assertions in production code: both
      // erode the guarantees tsc gives us. Use type annotations, `satisfies`,
      // narrowing, or `?.`/`??` instead. Disabled in tests (see overrides).
      "typescript/no-non-null-assertion": "error",
      "typescript/consistent-type-assertions": ["error", { assertionStyle: "never" }],
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "error",
      "react/jsx-key": "error",
      "react/no-array-index-key": "error",
      "react/no-unescaped-entities": "error",
      "react/jsx-no-duplicate-props": "error",
      "react/no-children-prop": "error",
      "react/no-danger-with-children": "error",
      "react/void-dom-elements-no-children": "error",
      "react/no-direct-mutation-state": "error",
      "react/jsx-no-target-blank": "error",
      "react/jsx-no-useless-fragment": "error",
      "react/self-closing-comp": "error",
      "react/no-unknown-property": "error",
      "react/jsx-no-comment-textnodes": "error",
      "react/no-string-refs": "error",
      "react/no-render-return-value": "error",
      "react/no-is-mounted": "error",
      "react/require-render-return": "error",
      "react/style-prop-object": "error",
      "react/no-danger": "error",
      // Type safety: no `any` (completes the assertion/non-null ban; off in
      // tests), and no `@ts-ignore`/`@ts-nocheck` escapes (use `@ts-expect-error`,
      // which self-removes when the underlying error is fixed).
      "typescript/no-explicit-any": "error",
      "typescript/ban-ts-comment": "error",
      "typescript/consistent-type-imports": "error",
      "typescript/no-import-type-side-effects": "error",
      // Import hygiene: no circular deps, no duplicate or self imports. The
      // resolution-based rules (default/named/namespace/no-unresolved) stay off:
      // oxlint's import resolver mis-handles our path aliases and package subpath
      // exports (same reason type-aware is off), so they false-positive.
      "import/no-cycle": "error",
      "import/no-duplicates": "error",
      "import/no-self-import": "error",
      "import/default": "off",
      "import/named": "off",
      "import/namespace": "off",
      // Enforce `===`, but keep the deliberate `== null` / `!= null` nullish idiom.
      eqeqeq: ["error", "always", { null: "ignore" }],
      // Modernization / small correctness wins.
      "unicorn/prefer-node-protocol": "error",
      "unicorn/throw-new-error": "error",
      "unicorn/error-message": "error",
      "unicorn/prefer-string-slice": "error",
      "unicorn/no-instanceof-array": "error",
      "unicorn/prefer-array-flat-map": "error",
      "promise/no-return-wrap": "error",
      "promise/valid-params": "error",
      "promise/param-names": "error",
      // Promote these from oxlint's default warn to error so they can't silently
      // accumulate; genuine intentional cases are inline-disabled with a reason.
      "no-unused-vars": "error",
      "no-control-regex": "error",
      "unicorn/no-new-array": "error",
      "unicorn/no-thenable": "error",
      // Type-aware rules (tsgolint) — the bug-catchers that need type info.
      // no-floating-promises catches unhandled async; the rest catch
      // "[object Object]" stringification, un-awaited thenables, bad sorts, etc.
      "typescript/no-floating-promises": "error",
      "typescript/no-misused-promises": "error",
      "typescript/no-base-to-string": "error",
      "typescript/restrict-template-expressions": "error",
      "typescript/await-thenable": "error",
      "typescript/require-array-sort-compare": "error",
      "typescript/no-meaningless-void-operator": "error",
      "typescript/no-useless-default-assignment": "error",
      // On in prod (catches a method reference that loses its `this`), but off in
      // tests (see overrides) where it only ever fires on mock method references.
      "typescript/unbound-method": "error",
      // Free type-aware footgun guards (0 findings today): for-in over arrays,
      // `delete arr[i]` (leaves holes), mixed string/number enums, duplicate
      // union members, redundant `=== true`, and Array#reduce type params.
      "typescript/no-for-in-array": "error",
      "typescript/no-array-delete": "error",
      "typescript/no-mixed-enums": "error",
      "typescript/no-duplicate-type-constituents": "error",
      "typescript/no-unnecessary-boolean-literal-compare": "error",
      "typescript/prefer-reduce-type-parameter": "error",
      // Off: flags the intentional `KnownLiterals | string` widening idiom
      // (e.g. `NodeJS.Platform | string`, `"now" | string`) we use to keep
      // autocomplete hints while accepting arbitrary strings. Stylistic, not a
      // bug-catcher like the rules above.
      "typescript/no-redundant-type-constituents": "off",
      // Accessibility (jsx-a11y recommended set).
      "jsx-a11y/alt-text": "error",
      "jsx-a11y/anchor-has-content": "error",
      "jsx-a11y/anchor-is-valid": "error",
      "jsx-a11y/aria-props": "error",
      "jsx-a11y/aria-role": "error",
      "jsx-a11y/aria-unsupported-elements": "error",
      "jsx-a11y/heading-has-content": "error",
      "jsx-a11y/img-redundant-alt": "error",
      "jsx-a11y/label-has-associated-control": "error",
      "jsx-a11y/control-has-associated-label": "error",
      "jsx-a11y/no-redundant-roles": "error",
      "jsx-a11y/no-aria-hidden-on-focusable": "error",
      "jsx-a11y/no-autofocus": "error",
      "jsx-a11y/role-has-required-aria-props": "error",
      "jsx-a11y/role-supports-aria-props": "error",
      "jsx-a11y/prefer-tag-over-role": "error",
      "jsx-a11y/click-events-have-key-events": "error",
      "jsx-a11y/no-static-element-interactions": "error",
      "jsx-a11y/no-noninteractive-element-interactions": "error",
      "jsx-a11y/interactive-supports-focus": "error",
    },
    plugins: [
      "react",
      "react-hooks",
      "typescript",
      "oxc",
      "unicorn",
      "import",
      "promise",
      "jsx-a11y",
    ],
    overrides: [
      {
        // Tests lean on assertions for mocks/fixtures where the type is known by
        // construction; only the assertion bans are relaxed here. Everything else
        // (including no-explicit-any) stays on in tests.
        files: ["**/*.test.ts", "**/*.test.tsx", "**/*.spec.ts", "**/*.spec.tsx", "**/tests/**"],
        rules: {
          "typescript/no-non-null-assertion": "off",
          "typescript/consistent-type-assertions": "off",
          // Only ever fires on mock/spy method references in tests; noise there.
          "typescript/unbound-method": "off",
        },
      },
    ],
    // Type-aware lint (tsgolint) is ON for the rules above. typeCheck stays OFF:
    // it surfaces raw tsc diagnostics as lint and mis-resolves our `@/*` aliases
    // and package subpath exports (false positives) — `tsc --noEmit` per package
    // remains the source of truth for types. The type-aware *rules* resolve types
    // fine within each package.
    options: { typeAware: true, typeCheck: false },
  },
});
