/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellDeveloperRouteImport } from './routes/_shell.developer'
import { Route as ShellErrorsRouteImport } from './routes/_shell.errors'
import { Route as ShellLogsRouteImport } from './routes/_shell.logs'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellTracesRouteImport } from './routes/_shell.traces'
import { Route as ShellErrorsFingerprintRouteImport } from './routes/_shell.errors.$fingerprint'
import { Route as ShellTracesTraceIdRouteImport } from './routes/_shell.traces.$traceId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDeveloperRoute = ShellDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => ShellRoute,
} as any)
const ShellErrorsRoute = ShellErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLogsRoute = ShellLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTracesRoute = ShellTracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => ShellRoute,
} as any)
const ShellErrorsFingerprintRoute = ShellErrorsFingerprintRouteImport.update({
  id: '/$fingerprint',
  path: '/$fingerprint',
  getParentRoute: () => ShellErrorsRoute,
} as any)
const ShellTracesTraceIdRoute = ShellTracesTraceIdRouteImport.update({
  id: '/$traceId',
  path: '/$traceId',
  getParentRoute: () => ShellTracesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/developer': typeof ShellDeveloperRoute
  '/errors': typeof ShellErrorsRouteWithChildren
  '/logs': typeof ShellLogsRoute
  '/settings': typeof ShellSettingsRoute
  '/traces': typeof ShellTracesRouteWithChildren
  '/errors/$fingerprint': typeof ShellErrorsFingerprintRoute
  '/traces/$traceId': typeof ShellTracesTraceIdRoute
}
export interface FileRoutesByTo {
  '/developer': typeof ShellDeveloperRoute
  '/errors': typeof ShellErrorsRouteWithChildren
  '/logs': typeof ShellLogsRoute
  '/settings': typeof ShellSettingsRoute
  '/traces': typeof ShellTracesRouteWithChildren
  '/': typeof ShellIndexRoute
  '/errors/$fingerprint': typeof ShellErrorsFingerprintRoute
  '/traces/$traceId': typeof ShellTracesTraceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/developer': typeof ShellDeveloperRoute
  '/_shell/errors': typeof ShellErrorsRouteWithChildren
  '/_shell/logs': typeof ShellLogsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/traces': typeof ShellTracesRouteWithChildren
  '/_shell/': typeof ShellIndexRoute
  '/_shell/errors/$fingerprint': typeof ShellErrorsFingerprintRoute
  '/_shell/traces/$traceId': typeof ShellTracesTraceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/developer'
    | '/errors'
    | '/logs'
    | '/settings'
    | '/traces'
    | '/errors/$fingerprint'
    | '/traces/$traceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/developer'
    | '/errors'
    | '/logs'
    | '/settings'
    | '/traces'
    | '/'
    | '/errors/$fingerprint'
    | '/traces/$traceId'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/developer'
    | '/_shell/errors'
    | '/_shell/logs'
    | '/_shell/settings'
    | '/_shell/traces'
    | '/_shell/'
    | '/_shell/errors/$fingerprint'
    | '/_shell/traces/$traceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/developer': {
      id: '/_shell/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof ShellDeveloperRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/errors': {
      id: '/_shell/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ShellErrorsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/logs': {
      id: '/_shell/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof ShellLogsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/traces': {
      id: '/_shell/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof ShellTracesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/errors/$fingerprint': {
      id: '/_shell/errors/$fingerprint'
      path: '/$fingerprint'
      fullPath: '/errors/$fingerprint'
      preLoaderRoute: typeof ShellErrorsFingerprintRouteImport
      parentRoute: typeof ShellErrorsRoute
    }
    '/_shell/traces/$traceId': {
      id: '/_shell/traces/$traceId'
      path: '/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof ShellTracesTraceIdRouteImport
      parentRoute: typeof ShellTracesRoute
    }
  }
}

interface ShellErrorsRouteChildren {
  ShellErrorsFingerprintRoute: typeof ShellErrorsFingerprintRoute
}

const ShellErrorsRouteChildren: ShellErrorsRouteChildren = {
  ShellErrorsFingerprintRoute: ShellErrorsFingerprintRoute,
}

const ShellErrorsRouteWithChildren = ShellErrorsRoute._addFileChildren(
  ShellErrorsRouteChildren,
)

interface ShellTracesRouteChildren {
  ShellTracesTraceIdRoute: typeof ShellTracesTraceIdRoute
}

const ShellTracesRouteChildren: ShellTracesRouteChildren = {
  ShellTracesTraceIdRoute: ShellTracesTraceIdRoute,
}

const ShellTracesRouteWithChildren = ShellTracesRoute._addFileChildren(
  ShellTracesRouteChildren,
)

interface ShellRouteChildren {
  ShellDeveloperRoute: typeof ShellDeveloperRoute
  ShellErrorsRoute: typeof ShellErrorsRouteWithChildren
  ShellLogsRoute: typeof ShellLogsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellTracesRoute: typeof ShellTracesRouteWithChildren
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDeveloperRoute: ShellDeveloperRoute,
  ShellErrorsRoute: ShellErrorsRouteWithChildren,
  ShellLogsRoute: ShellLogsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellTracesRoute: ShellTracesRouteWithChildren,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
