package semconv

const (
	EverrResourceUsageRecordKind             = "everr.resource_usage.record_kind"
	EverrResourceUsageRecordKindSample       = "sample"
	EverrResourceUsageRecordKindJobSummary   = "job_summary"
	EverrResourceUsageSchemaVersion          = "everr.resource_usage.schema_version"
	EverrResourceUsageSampleIntervalSeconds  = "everr.resource_usage.sample_interval_seconds"
	EverrResourceUsageCheckRunID             = "everr.resource_usage.check_run_id"
	EverrResourceUsageRunnerName             = "everr.resource_usage.runner.name"
	EverrResourceUsageRunnerOS               = "everr.resource_usage.runner.os"
	EverrResourceUsageRunnerArch             = "everr.resource_usage.runner.arch"
	EverrResourceUsageCPUUtilizationPct      = "everr.resource_usage.cpu.utilization_pct"
	EverrResourceUsageMemoryUsedBytes        = "everr.resource_usage.memory.used_bytes"
	EverrResourceUsageMemoryAvailableBytes   = "everr.resource_usage.memory.available_bytes"
	EverrResourceUsageDiskUsedBytes          = "everr.resource_usage.disk.used_bytes"
	EverrResourceUsageDiskAvailableBytes     = "everr.resource_usage.disk.available_bytes"
	EverrResourceUsageDiskUtilizationPct     = "everr.resource_usage.disk.utilization_pct"
	EverrResourceUsageLoad1                  = "everr.resource_usage.load1"
	EverrResourceUsageSampleCount            = "everr.resource_usage.sample_count"
	EverrResourceUsageDurationMs             = "everr.resource_usage.duration_ms"
	EverrResourceUsageCPUAvgPct              = "everr.resource_usage.cpu.avg_pct"
	EverrResourceUsageCPUP95Pct              = "everr.resource_usage.cpu.p95_pct"
	EverrResourceUsageCPUMaxPct              = "everr.resource_usage.cpu.max_pct"
	EverrResourceUsageMemoryAvgUsedBytes     = "everr.resource_usage.memory.avg_used_bytes"
	EverrResourceUsageMemoryMaxUsedBytes     = "everr.resource_usage.memory.max_used_bytes"
	EverrResourceUsageDiskPeakUsedBytes      = "everr.resource_usage.disk.peak_used_bytes"
	EverrResourceUsageDiskPeakUtilizationPct = "everr.resource_usage.disk.peak_utilization_pct"
	EverrResourceUsageLoad1Max               = "everr.resource_usage.load1.max"
)
