receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  githubactions:
    path: /webhook/github
    endpoint: 0.0.0.0:4321
    secret: WEBHOOKSECRETFROMGHAPP
    gh_api:
      auth:
        app_id: 1234
        installation_id: 6578
        private_key_path: /path/to/key.pem

processors:
  batch:

  resource:
    attributes:
      - action: insert
        key: ci.github.workflow.name
        from_attribute: ci.github.workflow.run.name
      - action: delete
        key: ci.github.workflow.run.name

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [5s, 15s, 30s, 1m, 5m, 10m, 30m]
      unit: s
    aggregation_temporality: 'AGGREGATION_TEMPORALITY_CUMULATIVE'
    exemplars:
      enabled: true

exporters:
  debug:
    verbosity: detailed
  clickhouse:
    endpoint: 'http://localhost:8123'
    username: 'default'
    database: 'default'
    # TODO: double check the following
    async_insert: false

service:
  pipelines:
    traces:
      receivers: [otlp, githubactions]
      processors: [resource]
      exporters: [spanmetrics, clickhouse, debug]
    logs:
      receivers: [otlp, githubactions]
      processors: []
      exporters: [clickhouse, debug]
    metrics:
      receivers: [spanmetrics]
      processors: []
      exporters: [clickhouse, debug]

  telemetry:
    metrics:
      level: detailed
    logs:
      level: debug
      encoding: 'json'
