name: Export Trace (Dash0)
on:
  workflow_run:
    workflows:
      - Build & Test App
      - Build & Test Collector
    types: [completed]

permissions:
  actions: read

jobs:
  otel-export-trace:
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    steps:
      - name: Export Workflow Trace
        uses: corentinmusard/otel-cicd-action@v2
        with:
          otlpEndpoint: ${{ secrets.DASH0_OTLP_ENDPOINT }}
          otlpHeaders: ${{ secrets.DASH0_OTLP_HEADERS }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
